import assert from 'node:assert/strict';import {createVersionedUnderstandingHandlers} from '../services/versioned-understanding-repository';import {loadActiveHypotheses} from '../services/evolving-understanding-repository';import {UnderstandingPgFixture} from './understanding-pg-fixture';
const pg=new UnderstandingPgFixture();pg.seed('recipients',[{id:'r',user_id:'u',birthday:null,anniversary:null}]);pg.seed('question_answers',[{id:'a',user_id:'u',recipient_id:'r',event_type:'Profile',event_year:2026,question_key:'communication',question_text:'How?',answer_text:'They prefer a phone call',was_skipped:false,trigger_type:'profile_gap',archived_at:null,created_at:'2026-01-01T00:00:00Z'}]);
for(const table of ['personal_cards','follow_up_questions','relationship_observation_versions','relationship_observation_heads','relationship_interpretations','relationship_interpretation_dependencies','relationship_interpretation_actions','relationship_interpretation_revisions','relationship_hypotheses','relationship_hypothesis_versions','relationship_hypothesis_heads','relationship_hypothesis_evidence','relationship_hypothesis_actions'])pg.seed(table,[]);
const handlers=createVersionedUnderstandingHandlers(pg.db,(req,res)=>{const user=req.headers['x-user-id'];if(typeof user!=='string'){res.status(401).json({error:'unauthenticated'});return null;}return user;});
async function call(name:keyof typeof handlers,body:Record<string,unknown>={},params:Record<string,string>={}){let status=200,data:any;const res={status(v:number){status=v;return res;},json(v:unknown){data=v;return res;}};await handlers[name]({headers:{'x-user-id':'u'},params:{id:'r',...params},body} as any,res as any);return{status,data};}
let timeline=await call('timeline');let hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.evidenceState,'support');assert.equal(hypothesis.confidence,null);assert.equal(hypothesis.support.length,1);assert.equal(hypothesis.dependencyVersionIds.length,1);
const observationVersion=hypothesis.dependencyVersionIds[0];const interpretation=await call('createInterpretation',{text:'Phone works best for them.',dependencyVersionIds:[observationVersion],operationId:'interpretation-1'});assert.equal(interpretation.status,201);timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.support.length,1,'interpretation does not add independent support');assert.ok(pg.tables.relationship_hypothesis_evidence.some(row=>row.interpretation_id===interpretation.data.id&&row.interpretation_revision===1),'exact interpretation revision provenance is durable');assert.equal(pg.tables.relationship_interpretation_revisions[0].text,'Phone works best for them.');
const beforeStrengtheningVersion=hypothesis.history.at(-1).id;pg.tables.question_answers.push({...pg.tables.question_answers[0],id:'strengthening',question_key:'communication_secondary',answer_text:'They prefer texts.',created_at:'2026-01-15T00:00:00Z'});timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.support.length,2,'a second underlying observation strengthens independent support');assert.notEqual(hypothesis.history.at(-1).id,beforeStrengtheningVersion,'strengthening appends an immutable successor');const strengthenedVersion=hypothesis.history.at(-1).id;assert.equal(pg.tables.relationship_hypothesis_heads[0].current_version_id,strengthenedVersion,'strengthened successor becomes current head');
pg.tables.question_answers.find(row=>row.id==='strengthening')!.archived_at='2026-01-20T00:00:00Z';timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.lifecycleState,'active','one remaining independent support keeps the hypothesis active');assert.equal(hypothesis.support.length,1,'removing one of two supports produces a weaker successor');assert.notEqual(hypothesis.history.at(-1).id,strengthenedVersion,'weakening appends a distinct immutable successor');assert.equal(pg.tables.relationship_hypothesis_versions.find(row=>row.id===strengthenedVersion)?.support_count,2,'the strengthened historical version remains unchanged');assert.equal(pg.tables.relationship_hypothesis_versions.find(row=>row.id===hypothesis.history.at(-1).id)?.support_count,1);assert.equal(pg.tables.relationship_hypothesis_heads[0].current_version_id,hypothesis.history.at(-1).id,'weaker successor becomes current head');
const versions=pg.tables.relationship_hypothesis_versions.length;await call('timeline');assert.equal(pg.tables.relationship_hypothesis_versions.length,versions,'unchanged reads are inert');
let action=await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'disagree-1'},{hypothesisId:hypothesis.id,action:'disagree'});assert.equal(action.status,200);const duplicate=await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'disagree-1'},{hypothesisId:hypothesis.id,action:'disagree'});assert.equal(duplicate.data.operationId,'disagree-1');
assert.equal((await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'disagree-1'},{hypothesisId:hypothesis.id,action:'confirm'})).status,409,'operation reuse must match the exact action');
assert.equal((await call('changeHypothesisLifecycle',{expectedRevision:1,operationId:'stale'},{hypothesisId:hypothesis.id,action:'withdraw'})).status,409);
pg.tables.question_answers[0].archived_at='2026-02-01T00:00:00Z';timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.lifecycleState,'retired');assert.equal(hypothesis.history.length,5);assert.ok(hypothesis.actionHistory.some((entry:any)=>entry.action==='disagree'));
assert.equal((await loadActiveHypotheses(pg.db as any,{userId:'u',recipientId:'r'})).length,0,'retired hypotheses never enter Brain context');
const retiredCount=pg.tables.relationship_hypothesis_versions.length;await call('timeline');assert.equal(pg.tables.relationship_hypothesis_versions.length,retiredCount);
pg.tables.question_answers[0].archived_at=null;timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.lifecycleState,'retired','restoring identical source content cannot revive');assert.equal(pg.tables.relationship_hypothesis_versions.length,retiredCount);
pg.tables.question_answers.push({...pg.tables.question_answers[0],id:'b',answer_text:'Email works well',archived_at:null,created_at:'2026-03-01T00:00:00Z'});timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.lifecycleState,'active','genuinely new support revives with a successor');assert.equal(hypothesis.history.length,6);assert.ok(pg.queries.some(q=>q.text.includes('serializable')));assert.ok(!pg.queries.some(q=>q.text.startsWith('update "relationship_hypothesis_versions"')));
assert.equal((await loadActiveHypotheses(pg.db as any,{userId:'u',recipientId:'r'})).length,0,'persistent disagreement suppresses Brain context');assert.equal((await loadActiveHypotheses(pg.db as any,{userId:'other',recipientId:'r'})).length,0);
assert.equal(hypothesis.responseState,'disagreed','disagreement survives reevaluation while confirmation does not inherit');
action=await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'reverse-1'},{hypothesisId:hypothesis.id,action:'reverse'});assert.equal(action.status,200);timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.responseState,'none','reversal clears suppression without confirming');
assert.equal((await loadActiveHypotheses(pg.db as any,{userId:'u',recipientId:'r'})).length,1,'reversal restores eligible uncertain context without endorsement');
action=await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'confirm-1'},{hypothesisId:hypothesis.id,action:'confirm'});assert.equal(action.status,200);timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.responseState,'confirmed');
action=await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'withdraw-1'},{hypothesisId:hypothesis.id,action:'withdraw'});assert.equal(action.status,200);timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.responseState,'withdrawn');assert.equal((await loadActiveHypotheses(pg.db as any,{userId:'u',recipientId:'r'})).length,0,'withdrawal removes active Brain authority');
action=await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'reverse-withdrawal'},{hypothesisId:hypothesis.id,action:'reverse'});assert.equal(action.status,200);timeline=await call('timeline');hypothesis=timeline.data.items.find((item:any)=>item.type==='hypothesis');assert.equal(hypothesis.responseState,'none');assert.equal((await call('changeHypothesisLifecycle',{expectedRevision:hypothesis.revision,operationId:'invalid-reverse'},{hypothesisId:hypothesis.id,action:'reverse'})).status,409);
const beforeRollback=structuredClone(pg.tables),publishedRevision=hypothesis.revision;pg.failOn=/insert into "relationship_hypothesis_actions"/;const failed=await call('changeHypothesisLifecycle',{expectedRevision:publishedRevision,operationId:'rollback-action'},{hypothesisId:hypothesis.id,action:'confirm'});assert.equal(failed.status,500);assert.match(failed.data.error,/no change was committed/i);assert.deepEqual(pg.tables,beforeRollback,'head and action roll back atomically');
assert.equal((await call('changeHypothesisLifecycle',{expectedRevision:publishedRevision,operationId:'cross-scope'},{hypothesisId:hypothesis.id,action:'confirm',id:'other'})).status,404);
console.log('evolving understanding actual Drizzle route lifecycle passed');

// A pre-rollout current interpretation can participate without fabricating earlier revisions.
const currentB=pg.tables.relationship_observation_versions.find(row=>row.source_record_id==='b')!;
pg.tables.relationship_interpretations.push({...pg.tables.relationship_interpretations[0],id:'existing-interpretation',revision:7,text:'Phone works best for them.',lifecycle_state:'active',confirmed_by_user_id:null,confirmed_at:null,endorsement_withdrawn_at:null});
pg.tables.relationship_interpretation_dependencies.push({interpretation_id:'existing-interpretation',observation_version_id:currentB.id});
await call('timeline');
const adopted=pg.tables.relationship_interpretation_revisions.filter(row=>row.interpretation_id==='existing-interpretation');
assert.deepEqual(adopted.map(row=>row.revision),[7],'capture only the current genuine revision, never invent versions 1-6');
assert.ok(pg.tables.relationship_hypothesis_evidence.some(row=>row.interpretation_id==='existing-interpretation'&&row.interpretation_revision===7));
const captured=structuredClone(adopted);await call('timeline');assert.deepEqual(pg.tables.relationship_interpretation_revisions.filter(row=>row.interpretation_id==='existing-interpretation'),captured,'unchanged current-revision capture is inert');
