import { createPgOpportunityFollowThroughRepository, followThroughLineageId, listOpportunityFollowThroughService, mutateOpportunityFollowThroughService, OpportunityFollowThroughConflictError, type OpportunityFollowThroughEvent } from "../brain/follow-through/index.js";
import { buildConciergeWorkspace } from "../brain/product/buildConciergeWorkspace.js";
import { UnderstandingPgFixture } from "./understanding-pg-fixture.js";
import { opportunityFollowThroughReceiptTable, opportunityFollowThroughTable } from "@workspace/db/schema";

class Fixture extends UnderstandingPgFixture { override async query(config:string|{text:string;rowMode?:string},parameters:unknown[]=[]){const result=await super.query(config,parameters);for(const row of this.tables.opportunity_follow_through_receipts??[])if(typeof row.response==="string")row.response=JSON.parse(row.response);for(const [table,keys] of [["opportunity_follow_through_events",["lineage_id","version"]],["opportunity_follow_through_receipts",["owner_id","idempotency_key"]]] as const){const seen=new Set<string>();for(const row of this.tables[table]??[]){const key=JSON.stringify(keys.map(k=>row[k]));if(seen.has(key))throw Object.assign(new Error("unique constraint"),{code:"23505"});seen.add(key);}}return result;} }
const fixture=new Fixture(),db=fixture.db,original=db.transaction.bind(db);let queue:Promise<unknown>=Promise.resolve();db.transaction=((...args:Parameters<typeof original>)=>{const op=queue.then(()=>original(...args));queue=op.catch(()=>undefined);return op;}) as typeof db.transaction;
const repository=createPgOpportunityFollowThroughRepository(async()=>({db,opportunityFollowThroughTable,opportunityFollowThroughReceiptTable}) as never);
const target={ownerId:"owner",recipientId:"recipient",opportunityId:"recipient:birthday",occurrenceCycleId:"annual:01-20:2026",relationshipId:"relationship",family:"birthday",sourceType:"brain_execution" as const,sourceId:"birthday"};
const base:OpportunityFollowThroughEvent={...target,id:"event-1",lineageId:followThroughLineageId(target,"action"),version:1,dimension:"action",value:"user_reported_completed",action:"set",provenance:"explicit_owner_report",verification:"user_reported",receivedAt:"2026-01-01T00:00:00.000Z",supersedesId:null,withdrawnEventId:null,idempotencyKey:"request-one",active:true};
await repository.append({event:base,expectedVersion:0,requestFingerprint:"same"});if((await repository.append({event:base,expectedVersion:0,requestFingerprint:"same"})).id!==base.id||(fixture.tables.opportunity_follow_through_events??[]).length!==1)throw Error("retry appended");
let conflict=false;try{await repository.append({event:base,expectedVersion:0,requestFingerprint:"changed"});}catch(e){conflict=e instanceof OpportunityFollowThroughConflictError;}if(!conflict)throw Error("key conflict missing");
let stale=false;try{await repository.append({event:{...base,id:"event-2",value:"planned",idempotencyKey:"request-two"},expectedVersion:0,requestFingerprint:"stale"});}catch(e){stale=e instanceof OpportunityFollowThroughConflictError;}if(!stale)throw Error("stale write accepted");
if((await repository.list({ownerId:"other",recipientIds:["recipient"]})).length||(await listOpportunityFollowThroughService("other","recipient",{repository,listOwnedRecipientIds:async()=>[]})).status!==404)throw Error("ownership isolation failed");
const opportunity:any={id:target.opportunityId,relationshipId:target.relationshipId,recipient:{id:target.recipientId,name:"R"},provenance:{sourceId:"birthday"},timing:{temporal:{occurrenceCycleId:target.occurrenceCycleId}}};const deps={repository,ownsRecipient:async(o:string,r:string)=>o==="owner"&&r==="recipient",resolveOpportunity:async()=>opportunity,now:()=>"2026-01-02T00:00:00.000Z"};
for(const hostile of [null,[],{recipientId:"recipient",opportunityId:target.opportunityId,occurrenceCycleId:target.occurrenceCycleId,dimension:"action",value:"externally_verified",expectedVersion:1,idempotencyKey:"hostile-1"},{recipientId:"recipient",followThroughEventId:base.id,dimension:"outcome",value:"went_well",verification:"external",expectedVersion:0,idempotencyKey:"hostile-2"}])if((await mutateOpportunityFollowThroughService("owner",hostile,deps)).status!==400)throw Error("hostile payload accepted");
const correction=await mutateOpportunityFollowThroughService("owner",{recipientId:"recipient",followThroughEventId:base.id,dimension:"action",value:"not_completed",expectedVersion:1,idempotencyKey:"correct-one"},{...deps,resolveOpportunity:async()=>null});if(correction.status!==201)throw Error("historical correction failed");
const outcome=await mutateOpportunityFollowThroughService("owner",{recipientId:"recipient",followThroughEventId:base.id,dimension:"outcome",value:"appreciated",expectedVersion:0,idempotencyKey:"outcome-one"},{...deps,resolveOpportunity:async()=>null});if(outcome.status!==201||(outcome.body.followThrough as OpportunityFollowThroughEvent).occurrenceCycleId!==target.occurrenceCycleId)throw Error("historical outcome rebound or failed");
const before=JSON.stringify(fixture.tables);fixture.failOn=/insert into "opportunity_follow_through_events"/;const failed=await mutateOpportunityFollowThroughService("owner",{recipientId:"recipient",followThroughEventId:(correction.body.followThrough as OpportunityFollowThroughEvent).id,dimension:"action",value:"planned",expectedVersion:2,idempotencyKey:"failure-one"},deps);if(failed.status!==503||JSON.stringify(fixture.tables)!==before)throw Error("atomic rollback failed");fixture.failOn=null;
let wrapped=false;try{await repository.append({event:{...(correction.body.followThrough as OpportunityFollowThroughEvent),id:"collision",version:2,value:"planned",idempotencyKey:"collision-one"},expectedVersion:2,requestFingerprint:"collision"});}catch(e){wrapped=e instanceof OpportunityFollowThroughConflictError;}if(!wrapped)throw Error("wrapped PG conflict missing");
const initialRace=await Promise.all(["planned","dismissed"].map((value,index)=>mutateOpportunityFollowThroughService("owner",{recipientId:"recipient",followThroughEventId:(correction.body.followThrough as OpportunityFollowThroughEvent).id,dimension:"action",value,expectedVersion:2,idempotencyKey:`race-key-${index}`},deps)));if(initialRace.filter(r=>r.status===201).length!==1||initialRace.filter(r=>r.status===409).length!==1)throw Error("concurrent stale writes did not produce one winner and one conflict");
const brain:any={loadResult:{loadedAt:"2026-01-01T00:00:00.000Z",relationshipContext:{}},extraction:{availableSignals:[{source:"event_timing",label:"birthday",value:"01-20"}]},decideResult:{decision:{outcome:"prepare_card"},confidence:60},actionPlan:{type:"prepare_card",category:"event",priority:"high",sourceRuleId:"birthday",primaryReason:"fixture",reasons:[],confidence:60,debugNotes:[]},selectedFollowUpQuestion:null};
const build=(follow:any=repository)=>buildConciergeWorkspace({userId:"owner",recipients:[{recipientId:"recipient",recipientName:"R"}],generatedAt:"2026-01-01T00:00:00.000Z",runBrain:async()=>brain,followThroughRepository:follow,feedbackRepository:{list:async()=>[],append:async()=>{throw Error("unused")}},temporalHistoryRepository:{listRetained:async()=>[],loadHistory:async()=>[],appendChange:async()=>undefined}});
const count=(fixture.tables.opportunity_follow_through_events??[]).length;const first=await build(),second=await build();if(first.opportunities.length!==1||second.opportunities.length!==1||(fixture.tables.opportunity_follow_through_events??[]).length!==count)throw Error("builder backfilled or lost retained state");const unavailable=await build({list:async()=>{throw Error("down")},append:async()=>{throw Error("down")}});if(unavailable.recommendations.length||unavailable.opportunities[0]?.recommendation)throw Error("read failure opened presentation");if(!fixture.queries.some(q=>q.text.includes('"owner_id"')&&q.text.includes('"recipient_id"')))throw Error("real scoped SQL not exercised");
console.log("Real Drizzle service, atomic receipts, conflicts, ownership, stored-lineage correction, outcome independence, and repeated builder reads passed.");

// Production-builder behavior uses the exact Opportunity produced by Brain, never a guessed cycle.
const runFor = (id:string,day='2026-01-01',repo:any=repository,feedback:any={list:async()=>[],append:async()=>{throw Error('unused')}}) => buildConciergeWorkspace({userId:'owner',recipients:[{recipientId:id,recipientName:id}],generatedAt:day+'T00:00:00.000Z',runBrain:async()=>brain,followThroughRepository:repo,feedbackRepository:feedback,temporalHistoryRepository:{listRetained:async()=>[],loadHistory:async()=>[],appendChange:async()=>undefined}});
const initial=(await runFor('live-r')).opportunities[0]!;
if(!initial.recommendation)throw Error('No eligible baseline for exact production test');
const liveDeps={repository,ownsRecipient:async(o:string,r:string)=>o==='owner'&&r==='live-r',resolveOpportunity:async()=>initial,now:()=> '2026-01-01T00:00:00.000Z'};
const report={recipientId:'live-r',opportunityId:initial.id,occurrenceCycleId:initial.timing.temporal!.occurrenceCycleId,dimension:'action',value:'user_reported_completed',expectedVersion:0,idempotencyKey:'live-completion-one'};
const completion=await mutateOpportunityFollowThroughService('owner',report,liveDeps);if(completion.status!==201)throw Error('Production target completion failed');
const completionEvent=completion.body.followThrough as OpportunityFollowThroughEvent;
const silent=await runFor('live-r');if(silent.recommendations.length||silent.insights.length||silent.opportunities.length!==1||silent.opportunities[0]!.recommendation)throw Error('Completed exact occurrence was not retained and silent');
const immutable=(o:typeof initial)=>JSON.stringify({evidence:o.provenance,confidence:o.confidence,timing:o.timing,relationship:o.relationshipId});if(immutable(initial)!==immutable(silent.opportunities[0]!))throw Error('Follow-through rewrote relationship knowledge');
const nextCycle=await runFor('live-r','2027-01-01');if(!nextCycle.opportunities[0]?.recommendation||nextCycle.opportunities[0].timing.temporal?.occurrenceCycleId===initial.timing.temporal!.occurrenceCycleId)throw Error('Old completion restrained a genuine new cycle');
const laterOutcome=await mutateOpportunityFollowThroughService('owner',{recipientId:'live-r',followThroughEventId:completionEvent.id,dimension:'outcome',value:'went_well',expectedVersion:0,idempotencyKey:'live-later-outcome'},{...liveDeps,resolveOpportunity:async()=>null});if(laterOutcome.status!==201||(laterOutcome.body.followThrough as OpportunityFollowThroughEvent).version!==1||(await runFor('live-r')).recommendations.length)throw Error('Separate historical outcome changed completion');
const historyBefore=await repository.list({ownerId:'owner',recipientIds:['live-r']});
const withdrawRequest={recipientId:'live-r',followThroughEventId:completionEvent.id,withdraw:true,expectedVersion:1,idempotencyKey:'live-withdraw-completion'};
const withdrawal=await mutateOpportunityFollowThroughService('owner',withdrawRequest,{...liveDeps,resolveOpportunity:async()=>null});if(withdrawal.status!==201||!(await runFor('live-r')).opportunities[0]?.recommendation)throw Error('Withdrawal did not remove only completion restraint');
const replayWithdrawal=await mutateOpportunityFollowThroughService('owner',withdrawRequest,{...liveDeps,resolveOpportunity:async()=>null});if(replayWithdrawal.status!==201||(replayWithdrawal.body.followThrough as OpportunityFollowThroughEvent).id!==(withdrawal.body.followThrough as OpportunityFollowThroughEvent).id)throw Error('Withdrawal retry duplicated history');
const historyAfter=await repository.list({ownerId:'owner',recipientIds:['live-r']});if(historyAfter.length!==historyBefore.length+1||JSON.stringify(historyAfter.filter(e=>e.id!==(withdrawal.body.followThrough as OpportunityFollowThroughEvent).id))!==JSON.stringify(historyBefore))throw Error('Withdrawal rewrote prior versions');
const replayAfterLoss=await mutateOpportunityFollowThroughService('owner',report,{...liveDeps,resolveOpportunity:async()=>null});if(replayAfterLoss.status!==201||(replayAfterLoss.body.followThrough as OpportunityFollowThroughEvent).id!==completionEvent.id)throw Error('Completed request lost replay after source disappearance');
const race=await Promise.all(['planned','not_completed'].map(value=>mutateOpportunityFollowThroughService('owner',{recipientId:'live-r',followThroughEventId:completionEvent.id,dimension:'action',value,expectedVersion:2,idempotencyKey:'race-'+value},{...liveDeps,resolveOpportunity:async()=>null})));if(race.filter(r=>r.status===201).length!==1||race.filter(r=>r.status===409).length!==1)throw Error('Concurrent stale writes did not yield winner/conflict');
const ownerFailure=await mutateOpportunityFollowThroughService('owner',{...report,idempotencyKey:'ownership-read-failure'},{...liveDeps,ownsRecipient:async()=>{throw Error('down')}});if(ownerFailure.status!==503)throw Error('Ownership failure fabricated success');
const readerFailure=await listOpportunityFollowThroughService('owner',null,{repository,listOwnedRecipientIds:async()=>{throw Error('down')}});if(readerFailure.status!==503)throw Error('History ownership failure fabricated empty success');
// A known scope mismatch cannot suppress the same recipient/cycle.
for(const override of [{ownerId:'other'},{relationshipId:'different-relationship'},{family:'anniversary',sourceId:'anniversary'}]){
 const foreign={...completionEvent,...override};const result=await runFor('live-r','2026-01-01',{list:async()=>[foreign],append:async()=>{throw Error('unused')}});
 if(!result.opportunities[0]?.recommendation)throw Error('Foreign owner/relationship/source report affected current Opportunity');
}
console.log('Exact completion restraint, independent outcome, immutable evidence, future cycle, historical withdrawal/replay, scoped projection, and concurrent CAS passed.');

const capRecipients=Array.from({length:5},(_,i)=>({recipientId:'follow-cap-'+i,recipientName:'Cap '+i}));
const capBuild=()=>buildConciergeWorkspace({userId:'owner',recipients:capRecipients,generatedAt:'2026-01-01T00:00:00.000Z',runBrain:async()=>brain,followThroughRepository:repository,feedbackRepository:{list:async()=>[],append:async()=>{throw Error('unused')}},temporalHistoryRepository:{listRetained:async()=>[],loadHistory:async()=>[],appendChange:async()=>undefined}});
const capBaseline=await capBuild();const presented=capBaseline.opportunities.filter(o=>o.presentation.recommendationEligible);if(presented.length!==3)throw Error('Maximum-three baseline missing');
for(const [i,o] of presented.entries()){
 const result=await mutateOpportunityFollowThroughService('owner',{recipientId:o.recipient.id,opportunityId:o.id,occurrenceCycleId:o.timing.temporal!.occurrenceCycleId,dimension:'action',value:'no_longer_relevant',expectedVersion:0,idempotencyKey:'cap-completion-'+i},{repository,ownsRecipient:async(owner,id)=>owner==='owner'&&capRecipients.some(r=>r.recipientId===id),resolveOpportunity:async(_owner,id,key)=>capBaseline.opportunities.find(item=>item.id===key&&item.recipient.id===id)??null});
 if(result.status!==201)throw Error('Cap report rejected');
}
const capAfter=await capBuild();if(capAfter.opportunities.length!==5||capAfter.opportunities.some(o=>o.presentation.recommendationEligible))throw Error('Follow-through backfilled slots or erased Opportunities');
console.log('Five Opportunities retained, three original slots restrained, no forced backfill.');
