import { executeRelationshipAnswerMutation, projectActiveRelationshipMemoryEvidence, type RelationshipAnswerRecord, type RelationshipAnswerRepository } from "../services/relationship-memory-evidence.js";
import type { QuestionAnswer } from "@workspace/db";
const rows=new Map<string,RelationshipAnswerRecord>([["a",{id:"a",userId:"u1",recipientId:"r1",triggerType:"fresh_update",answerText:"before",archivedAt:null}],["unsupported",{id:"unsupported",userId:"u1",recipientId:"r1",triggerType:"event_briefing",answerText:"brief",archivedAt:null}]]); let writes=0;
const repository:RelationshipAnswerRepository={async read(s){const r=rows.get(s.answerId);return r&&r.userId===s.userId&&r.recipientId===s.recipientId?{...r}:null;},async write(s,m,expected){const r=rows.get(s.answerId);if(!r||r.userId!==s.userId||r.recipientId!==s.recipientId||(r.archivedAt!==null)!==expected)return null;writes++;const u={...r,answerText:m.action==="edit"?m.answerText:r.answerText,archivedAt:m.action==="archive"?new Date("2026-01-02Z"):m.action==="restore"?null:r.archivedAt};rows.set(r.id,u);return{...u};}};
const scope={userId:"u1",recipientId:"r1",answerId:"a"}; let result=await executeRelationshipAnswerMutation(repository,scope,{action:"edit",answerText:" corrected "});
if(!result.ok||rows.get("a")?.answerText!=="corrected")throw new Error("edit/reload failed");const corrected=projectActiveRelationshipMemoryEvidence({answers:[...rows.values()] as QuestionAnswer[]}).find(e=>e.evidenceId==="a");if(corrected?.summary!=="corrected")throw new Error("corrected text did not survive production projection reload"); result=await executeRelationshipAnswerMutation(repository,scope,{action:"archive"});if(!result.ok)throw new Error("archive failed");
const active=()=>projectActiveRelationshipMemoryEvidence({answers:[...rows.values()] as QuestionAnswer[]});if(active().some(e=>e.evidenceId==="a"))throw new Error("archive remained active");
const count=writes;result=await executeRelationshipAnswerMutation(repository,scope,{action:"archive"});if(result.ok||writes!==count)throw new Error("duplicate archive mutated");result=await executeRelationshipAnswerMutation(repository,scope,{action:"restore"});if(!result.ok||!active().some(e=>e.evidenceId==="a"))throw new Error("restore failed");
for(const denied of [{...scope,answerId:"missing"},{...scope,userId:"u2"},{...scope,recipientId:"r2"},{...scope,answerId:"unsupported"}]){const before=JSON.stringify([...rows]);const n=writes;const d=await executeRelationshipAnswerMutation(repository,denied,{action:"edit",answerText:"bad"});if(d.ok||writes!==n||JSON.stringify([...rows])!==before)throw new Error("denial changed state");}
console.log("relationship memory executable lifecycle passed");
