import assert from 'node:assert/strict';
import {currentObservationVersions,observationHistory,exactDependenciesValid,projectActiveUnderstanding,truthfulIso} from '../services/versioned-understanding';
const scope={userId:'u',recipientId:'r'};
const original={...scope,id:'v1',sourceRecordId:'answer',version:1,lifecycleState:'active',text:'Reported story',relationshipId:null,sourceKind:'user_report',semanticClassification:'reported_information',sourceProvenance:{table:'question_answers'},recordedAt:'2026-09-01T00:00:00Z',observedAt:null,occurredAt:null,confidence:null,actorUserId:'u'};
const versions=Object.freeze([Object.freeze(original),Object.freeze({...original,id:'v2',version:2,text:'Corrected report'})]);
assert.equal(currentObservationVersions(versions,scope)[0].id,'v2');
assert.equal(observationHistory(versions)[0].lifecycleState,'superseded');
assert.equal(observationHistory(versions)[0].stateAtRevision,'active');
assert.equal(original.lifecycleState,'active');assert.equal(original.text,'Reported story');
assert.equal(exactDependenciesValid(versions,['v1'],scope),false);
assert.equal(exactDependenciesValid(versions,['v2'],scope),true);
assert.equal(exactDependenciesValid(versions,['v2'],{...scope,userId:'other'}),false);
assert.equal(exactDependenciesValid(versions,[],scope),false);
const interpretation={...scope,id:'i',text:'Possibly meaningful',relationshipId:null,confidence:null,lifecycleState:'active',createdAt:'2026-09-02T00:00:00Z',actorUserId:'u',confirmedByUserId:'u',confirmedAt:'2026-09-03T00:00:00Z',endorsementWithdrawnAt:null,revision:2};
assert.equal(projectActiveUnderstanding(versions,[interpretation],[{interpretationId:'i',observationVersionId:'v1'}],scope).interpretations.length,0);
const active=projectActiveUnderstanding(versions,[interpretation],[{interpretationId:'i',observationVersionId:'v2'}],scope);
assert.equal(active.interpretations[0].uncertain,true);assert.equal(active.interpretations[0].confidence,null);
assert.equal(active.interpretations[0].semanticClassification,'uncertain_interpretation');
assert.equal(active.observations[0].relationshipId,null);assert.equal(active.observations[0].observedAt,null);
assert.equal(projectActiveUnderstanding(versions,[{...interpretation,lifecycleState:'withdrawn'}],[{interpretationId:'i',observationVersionId:'v2'}],scope).interpretations.length,0);
assert.equal(truthfulIso('invalid'),null);assert.equal(truthfulIso(null),null);
assert.equal(currentObservationVersions([{...original,sourceRecordId:null,id:'a'},{...original,sourceRecordId:null,id:'b'}]).length,2);
console.log('versioned understanding production projections passed');
