export {
  FiButton,
  buttonAccessibility,
  buttonAccessibilityChecks,
  fiButtonSizes,
  fiButtonVariants,
  getFiButtonClassName,
  hasAccessibleName,
  verifyButtonAccessibility,
} from "@/app/components/button";
export type { FiButtonProps, FiButtonSize, FiButtonVariant } from "@/app/components/button";

export {
  FiAutocomplete,
  FiCheckbox,
  FiDateInput,
  FiEmailInput,
  FiField,
  FiInput,
  FiMultiSelect,
  FiPasswordInput,
  FiPhoneInput,
  FiRadio,
  FiRadioGroup,
  FiSearchInput,
  FiSelect,
  FiSlider,
  FiSwitch,
  FiTextarea,
  buildDescribedBy,
  fiInputStates,
  getFiInputClassName,
  inputAccessibility,
  inputAccessibilityChecks,
  verifyInputAccessibility,
} from "@/app/components/input";
export type {
  FiAutocompleteOption,
  FiAutocompleteProps,
  FiCheckboxProps,
  FiFieldProps,
  FiInputProps,
  FiInputState,
  FiInputType,
  FiMultiSelectProps,
  FiRadioGroupProps,
  FiRadioProps,
  FiSelectProps,
  FiSliderProps,
  FiSwitchProps,
  FiTextareaProps,
} from "@/app/components/input";

export {
  FiAiRecommendationCard,
  FiAnalyticsCard,
  FiBillingCard,
  FiCard,
  FiCardContent,
  FiCardDescription,
  FiCardFooter,
  FiCardHeader,
  FiCardLoading,
  FiCardSkeleton,
  FiCardTitle,
  FiDashboardCard,
  FiEmptyStateCard,
  FiNotificationCard,
  FiRecipientCard,
  FiTimelineCard,
  cardAccessibility,
  cardAccessibilityChecks,
  fiCardVariants,
  getFiCardClassName,
  isCardAccessibilityValid,
  verifyCardAccessibility,
} from "@/app/components/card";
export type {
  FiCardLoadingProps,
  FiCardProps,
  FiCardSkeletonProps,
  FiCardVariant,
} from "@/app/components/card";

export {
  FiAvatar,
  FiAvatarGroup,
  FiConciergeAvatar,
  FiInitialAvatar,
  FiRecipientAvatar,
  FiSystemAvatar,
  FiUserAvatar,
  avatarAccessibility,
  avatarAccessibilityChecks,
  fiAvatarSizes,
  fiAvatarStatusTypes,
  getFiAvatarClassName,
  verifyAvatarAccessibility,
} from "@/app/components/avatar";
export type {
  FiAvatarGroupItem,
  FiAvatarGroupProps,
  FiAvatarProps,
  FiAvatarSize,
  FiAvatarStatus,
  FiAvatarVariant,
} from "@/app/components/avatar";

export {
  FiAiBadge,
  FiBadge,
  FiBrowniePointsBadge,
  FiCalendarBadge,
  FiNotificationBadge,
  FiPriorityBadge,
  FiRelationshipHealthBadge,
  FiStatusBadge,
  FiSubscriptionBadge,
  FiVerificationBadge,
  badgeAccessibility,
  badgeAccessibilityChecks,
  fiBadgeSizes,
  fiBadgeStatusTones,
  formatNotificationCount,
  getFiBadgeClassName,
  isBadgeTextConcise,
  verifyBadgeAccessibility,
} from "@/app/components/badge";
export type {
  FiAiBadgeProps,
  FiBadgeProps,
  FiBadgeSize,
  FiBadgeStatusTone,
  FiBrowniePointsBadgeProps,
  FiCalendarBadgeProps,
  FiCalendarBadgeStatus,
  FiNotificationBadgeProps,
  FiPriorityBadgeProps,
  FiPriorityLevel,
  FiRelationshipHealthBadgeProps,
  FiRelationshipHealthLevel,
  FiStatusBadgeProps,
  FiSubscriptionBadgeProps,
  FiSubscriptionStatus,
  FiVerificationBadgeProps,
} from "@/app/components/badge";

export {
  FiAiGenerationProgress,
  FiBrowniePointsProgress,
  FiCircularProgress,
  FiCompletionProgress,
  FiLinearProgress,
  FiProgress,
  FiRelationshipHealthRing,
  FiStepProgress,
  FiUploadProgress,
  aiGenerationSteps,
  fiProgressSizes,
  fiProgressTones,
  getFiLinearProgressClassName,
  progressAccessibility,
  progressAccessibilityChecks,
  verifyProgressAccessibility,
} from "@/app/components/progress";
export type {
  FiAiGenerationProgressProps,
  FiAiGenerationStepId,
  FiBrowniePointsProgressProps,
  FiCircularProgressProps,
  FiCompletionProgressProps,
  FiCompletionVariant,
  FiLinearProgressProps,
  FiProgressSize,
  FiProgressTone,
  FiRelationshipHealthRingProps,
  FiStepProgressProps,
  FiStepProgressStep,
  FiStepProgressVariant,
  FiUploadProgressProps,
} from "@/app/components/progress";

export {
  FiAlert,
  FiAlertActions,
  FiAlertDescription,
  FiAlertTitle,
  FiBanner,
  FiConfirmationBanner,
  FiErrorMessage,
  FiInlineMessage,
  FiLoadingIndicator,
  FiOfflineBanner,
  FiRetryBanner,
  FiSuccessMessage,
  FiToast,
  FiToastViewport,
  FiWarningMessage,
  feedbackAccessibility,
  feedbackAccessibilityChecks,
  fiAlertTones,
  fiFeedbackTones,
  getFiAlertClassName,
  verifyFeedbackAccessibility,
} from "@/app/components/feedback";
export type {
  FiAlertProps,
  FiAlertTone,
  FiBannerProps,
  FiConfirmationBannerProps,
  FiFeedbackTone,
  FiInlineMessageProps,
  FiInlineMessageTone,
  FiLoadingIndicatorProps,
  FiLoadingIndicatorSize,
  FiMessageAlertProps,
  FiOfflineBannerProps,
  FiRetryBannerProps,
  FiToastProps,
  FiToastViewportProps,
} from "@/app/components/feedback";

export {
  FiBackNavigation,
  FiBreadcrumb,
  FiBreadcrumbItem,
  FiBreadcrumbLink,
  FiBreadcrumbList,
  FiBreadcrumbPage,
  FiCommandPalette,
  FiFooterNavigation,
  FiMobileNavigation,
  FiNavItem,
  FiNotificationMenu,
  FiSearchBar,
  FiSidebar,
  FiSidebarNav,
  FiTopNavigation,
  FiTopNavList,
  FiUserMenu,
  getFiNavItemClassName,
  navigationAccessibility,
  navigationAccessibilityChecks,
  verifyNavigationAccessibility,
} from "@/app/components/navigation";
export type {
  FiBackNavigationProps,
  FiBreadcrumbProps,
  FiCommandPaletteItemData,
  FiCommandPaletteProps,
  FiFooterNavigationProps,
  FiMobileNavigationProps,
  FiNavItemProps,
  FiNavItemVariant,
  FiNavigationItem,
  FiNotificationMenuItemData,
  FiNotificationMenuProps,
  FiSearchBarProps,
  FiSidebarMode,
  FiSidebarNavProps,
  FiSidebarProps,
  FiTopNavigationProps,
  FiUserMenuItemData,
  FiUserMenuProps,
} from "@/app/components/navigation";

export {
  FiConfirmationDialog,
  FiDeleteDialog,
  FiDialog,
  FiDialogBody,
  FiDialogClose,
  FiDialogDescription,
  FiDialogFooter,
  FiDialogHeader,
  FiDialogTitle,
  FiErrorDialog,
  FiFormDialog,
  FiInformationDialog,
  FiLoadingDialog,
  FiUpgradeDialog,
  dialogAccessibility,
  dialogAccessibilityChecks,
  getFiDialogClassName,
  verifyDialogAccessibility,
} from "@/app/components/dialog";
export type {
  FiConfirmationDialogProps,
  FiDeleteDialogProps,
  FiDialogProps,
  FiDialogSize,
  FiDialogVariant,
  FiErrorDialogProps,
  FiFormDialogProps,
  FiInformationDialogProps,
  FiLoadingDialogProps,
  FiUpgradeDialogProps,
} from "@/app/components/dialog";

export {
  FiAdminEmptyState,
  FiAiConciergeEmptyState,
  FiBillingEmptyState,
  FiCalendarEmptyState,
  FiDashboardEmptyState,
  FiEmptyState,
  FiEmptyStateActions,
  FiEmptyStateContent,
  FiEmptyStateDescription,
  FiEmptyStateIcon,
  FiEmptyStateIllustration,
  FiEmptyStateLayout,
  FiEmptyStateTitle,
  FiNotificationEmptyState,
  FiRecipientEmptyState,
  FiSearchEmptyState,
  FiTimelineEmptyState,
  buildEmptyStateRegionLabel,
  emptyStateAccessibility,
  emptyStateAccessibilityChecks,
  emptyStateDefaults,
  getFiEmptyStateClassName,
  verifyEmptyStateAccessibility,
} from "@/app/components/empty-state";
export type {
  FiEmptyStateCopy,
  FiEmptyStateIllustrationProps,
  FiEmptyStateLayoutProps,
  FiEmptyStatePresetProps,
  FiEmptyStateProps,
  FiEmptyStateVariant,
} from "@/app/components/empty-state";

export {
  FiAiGenerationSkeleton,
  FiBillingSkeleton,
  FiCalendarSkeleton,
  FiCardLoadingSkeleton,
  FiDashboardSkeleton,
  FiListSkeleton,
  FiLoadingRegion,
  FiPageSkeleton,
  FiRecipientSkeleton,
  FiSearchSkeleton,
  FiSkeleton,
  FiSkeletonRow,
  FiSkeletonText,
  FiTimelineSkeleton,
  buildLoadingRegionLabel,
  loadingAccessibility,
  loadingAccessibilityChecks,
  loadingSkeletonDefaults,
  getFiSkeletonClassName,
  verifyLoadingAccessibility,
} from "@/app/components/loading";
export type {
  FiAiGenerationSkeletonProps,
  FiLoadingRegionProps,
  FiLoadingSkeletonPresetProps,
  FiLoadingSkeletonVariant,
  FiSkeletonProps,
  FiSkeletonRowProps,
  FiSkeletonTextProps,
} from "@/app/components/loading";

export {
  FiGlobalSearch,
  FiGlobalSearchTrigger,
  FiSearchErrorState,
  FiSearchFilters,
  FiSearchHighlight,
  FiSearchPage,
  FiSearchResultItem,
  FiSearchResults,
  FiSearchSuggestions,
  buildSearchDialogLabel,
  searchAccessibility,
  searchAccessibilityChecks,
  verifySearchAccessibility,
} from "@/app/components/search";
export type {
  FiGlobalSearchProps,
  FiGlobalSearchTriggerProps,
  FiSearchErrorStateProps,
  FiSearchFiltersProps,
  FiSearchHighlightProps,
  FiSearchResultItemProps,
  FiSearchResultsProps,
  FiSearchSuggestionsProps,
} from "@/app/components/search";

export {
  FiNotificationCenter,
  FiNotificationCenterTrigger,
  FiNotificationErrorState,
  FiNotificationFilters,
  FiNotificationGroup,
  FiNotificationItem,
  FiNotificationList,
  FiNotificationSearch,
  FiNotificationSkeleton,
  buildNotificationDrawerLabel,
  notificationAccessibility,
  notificationAccessibilityChecks,
  verifyNotificationAccessibility,
} from "@/app/components/notification";
export type {
  FiNotificationCenterProps,
  FiNotificationCenterTriggerProps,
  FiNotificationErrorStateProps,
  FiNotificationFiltersProps,
  FiNotificationGroupProps,
  FiNotificationItemProps,
  FiNotificationListProps,
  FiNotificationSearchProps,
  FiNotificationSkeletonProps,
} from "@/app/components/notification";

export {
  FiCommunicationHistoryPanel,
  FiNotificationCategoriesPanel,
  FiNotificationPreferencesPanel,
  FiNotificationsInboxPanel,
  FiNotificationsPage,
} from "@/app/components/notifications";

export {
  FiRelationshipTimeline,
  FiTimelineArchiveConfirm,
  FiTimelineFilters,
  FiTimelineGroup,
  FiTimelineInlineEdit,
  FiTimelineItem,
  FiTimelineList,
  FiTimelineSearch,
  FiTimelineErrorState,
  buildTimelineRegionLabel,
  timelineAccessibility,
  timelineAccessibilityChecks,
  verifyTimelineAccessibility,
} from "@/app/components/timeline";
export type {
  FiRelationshipTimelineProps,
  FiTimelineArchiveConfirmProps,
  FiTimelineErrorStateProps,
  FiTimelineFiltersProps,
  FiTimelineGroupProps,
  FiTimelineInlineEditProps,
  FiTimelineItemProps,
  FiTimelineListProps,
  FiTimelineSearchProps,
} from "@/app/components/timeline";

export {
  FiRelationshipHealthPanel,
  FiRelationshipHealthSummary,
  FiRelationshipHealthExplanation,
  FiRelationshipHealthTrend,
  FiRelationshipHealthSuggestions,
  FiRelationshipHealthSkeleton,
  FiRelationshipHealthEmptyState,
  FiRelationshipHealthErrorState,
  buildRelationshipHealthRegionLabel,
  relationshipHealthAccessibility,
  relationshipHealthAccessibilityChecks,
  verifyRelationshipHealthAccessibility,
} from "@/app/components/relationship-health";
export type {
  FiRelationshipHealthPanelProps,
  FiRelationshipHealthSummaryProps,
  FiRelationshipHealthExplanationProps,
  FiRelationshipHealthTrendProps,
  FiRelationshipHealthSuggestionsProps,
  FiRelationshipHealthSkeletonProps,
  FiRelationshipHealthEmptyStateProps,
  FiRelationshipHealthErrorStateProps,
} from "@/app/components/relationship-health";

export {
  FiBrowniePointsPanel,
  FiBrowniePointsDisplay,
  FiBrowniePointsHistory,
  FiBrowniePointsMilestone,
  FiBrowniePointsSkeleton,
  FiBrowniePointsErrorState,
  buildBrowniePointsRegionLabel,
  browniePointsAccessibility,
  browniePointsAccessibilityChecks,
  verifyBrowniePointsAccessibility,
} from "@/app/components/brownie-points";
export type {
  FiBrowniePointsPanelProps,
  FiBrowniePointsDisplayProps,
  FiBrowniePointsHistoryProps,
  FiBrowniePointsMilestoneProps,
  FiBrowniePointsSkeletonProps,
  FiBrowniePointsErrorStateProps,
} from "@/app/components/brownie-points";

export {
  FiConciergeSuggestionsPanel,
  FiConciergeSuggestionCard,
  FiConciergeSuggestionsList,
  FiConciergeSuggestionsSkeleton,
  FiConciergeSuggestionsEmptyState,
  FiConciergeSuggestionsErrorState,
  buildConciergeSuggestionsRegionLabel,
  conciergeSuggestionsAccessibility,
  conciergeSuggestionsAccessibilityChecks,
  verifyConciergeSuggestionsAccessibility,
} from "@/app/components/concierge-suggestions";
export type {
  FiConciergeSuggestionsPanelProps,
  FiConciergeSuggestionCardProps,
  FiConciergeSuggestionsListProps,
  FiConciergeSuggestionsSkeletonProps,
  FiConciergeSuggestionsEmptyStateProps,
  FiConciergeSuggestionsErrorStateProps,
} from "@/app/components/concierge-suggestions";

export {
  FiCalendarPage,
  FiRelationshipCalendarPanel,
  FiCalendarAgenda,
  FiCalendarEventDetails,
  FiCalendarMonthly,
  FiCalendarWeekly,
  FiCalendarDailyAgenda,
  FiCalendarEventCard,
  FiCalendarEventIndicator,
  FiCalendarEventIndicators,
  FiCalendarDatePicker,
  FiCalendarFilters,
  FiCalendarSearch,
  FiCalendarLoadingSkeleton,
  FiCalendarPanelEmptyState,
  FiCalendarErrorState,
  buildCalendarRegionLabel,
  calendarAccessibility,
  calendarAccessibilityChecks,
  verifyCalendarAccessibility,
} from "@/app/components/calendar";
export type {
  FiRelationshipCalendarPanelProps,
  FiCalendarMonthlyProps,
  FiCalendarWeeklyProps,
  FiCalendarDailyAgendaProps,
  FiCalendarEventCardProps,
  FiCalendarEventIndicatorProps,
  FiCalendarDatePickerProps,
  FiCalendarFiltersProps,
  FiCalendarSearchProps,
  FiCalendarPanelEmptyStateProps,
  FiCalendarErrorStateProps,
  FiCalendarAgendaProps,
  FiCalendarEventDetailsProps,
} from "@/app/components/calendar";

export {
  FiRecipientPanel,
  FiRecipientSummary,
  FiRecipientRelationshipOverview,
  FiRecipientQuickActions,
  FiRecipientMemoryPreview,
  FiRecipientMilestones,
  FiRecipientActivitySummaryPanel,
  FiRecipientCardHistory,
  FiRecipientStatusIndicators,
  FiRecipientLoadingSkeleton,
  FiRecipientPanelEmptyState,
  FiRecipientErrorState,
  buildRecipientRegionLabel,
  recipientAccessibility,
  recipientAccessibilityChecks,
  verifyRecipientAccessibility,
} from "@/app/components/recipient";
export type {
  FiRecipientPanelProps,
  FiRecipientSummaryProps,
  FiRecipientRelationshipOverviewProps,
  FiRecipientQuickActionsProps,
  FiRecipientMemoryPreviewProps,
  FiRecipientMilestonesProps,
  FiRecipientActivitySummaryProps,
  FiRecipientCardHistoryProps,
  FiRecipientStatusIndicatorsProps,
  FiRecipientPanelEmptyStateProps,
  FiRecipientErrorStateProps,
} from "@/app/components/recipient";

export {
  FiAiPanel,
  FiAiGenerationIndicator,
  FiAiDraftingProgress,
  FiAiRecommendationPanelCard,
  FiAiSuggestionList,
  FiAiConfidenceMessage,
  FiAiRetryExperience,
  FiAiPanelLoadingSkeleton,
  FiAiPanelEmptyState,
  aiAccessibility,
  aiAccessibilityChecks,
  buildAiRegionLabel,
  verifyAiAccessibility,
} from "@/app/components/ai";
export type {
  FiAiPanelProps,
  FiAiGenerationIndicatorProps,
  FiAiDraftingProgressProps,
  FiAiRecommendationPanelCardProps,
  FiAiSuggestionListProps,
  FiAiConfidenceMessageProps,
  FiAiRetryExperienceProps,
  FiAiPanelLoadingSkeletonProps,
  FiAiPanelEmptyStateProps,
} from "@/app/components/ai";

export {
  FiAiConciergePage,
  FiConciergeConversationPanel,
  FiConciergeWorkspacePanel,
  buildConciergeConversationLabel,
  conciergeAccessibility,
  conciergeAccessibilityChecks,
  verifyConciergeAccessibility,
} from "@/app/components/ai-concierge";

export { FiSystemVerificationPage } from "@/app/components/verification";
export { FiLaunchReadinessPage } from "@/app/components/launch-readiness";
export { FiSkipLink } from "@/app/components/navigation/FiSkipLink";

export {
  FiDashboardPage,
  FiDashboardShell,
  FiDashboardHero,
  FiDashboardQuickActions,
  FiDashboardUpcomingCards,
  FiDashboardRelationshipSpotlight,
  FiDashboardRelationshipHealthSummary,
  FiDashboardBrowniePointsSummary,
  FiDashboardSuggestedActions,
  FiDashboardRecentActivity,
  FiDashboardPendingReview,
  FiDashboardAttentionItems,
  FiDashboardFooter,
  FiDashboardPanelEmptyState,
  FiDashboardErrorState,
  FiDashboardLoadingState,
  FiDashboardFirstTimeExperience,
  dashboardAccessibility,
  dashboardAccessibilityChecks,
  buildDashboardRegionLabel,
  verifyDashboardAccessibility,
} from "@/app/components/dashboard";
export type {
  FiDashboardShellProps,
  FiDashboardHeroProps,
  FiDashboardQuickActionsProps,
  FiDashboardUpcomingCardsProps,
  FiDashboardRelationshipSpotlightProps,
  FiDashboardRecentActivityProps,
  FiDashboardPendingReviewProps,
  FiDashboardAttentionItemsProps,
  FiDashboardFooterProps,
  FiDashboardPanelEmptyStateProps,
  FiDashboardErrorStateProps,
  FiDashboardFirstTimeExperienceProps,
} from "@/app/components/dashboard";

export {
  FiRelationshipProfilePage,
  FiRelationshipProfileShell,
  FiRelationshipProfileNavigation,
  FiRelationshipProfileHeader,
  FiRelationshipProfileHealthBar,
  FiRelationshipProfileInsights,
  FiRelationshipProfileOccasions,
  FiRelationshipProfileComingUp,
  FiRelationshipProfileMemories,
  FiRelationshipProfileFollowUp,
  FiRelationshipProfileProfileFields,
  FiRelationshipProfileCards,
  FiRelationshipProfileTimelineSection,
  FiRelationshipProfileLoadingState,
  relationshipProfileAccessibility,
  relationshipProfileAccessibilityChecks,
  buildRelationshipProfileRegionLabel,
  verifyRelationshipProfileAccessibility,
} from "@/app/components/relationship-profile";
export type {
  FiRelationshipProfileShellProps,
  FiRelationshipProfileHeaderProps,
} from "@/app/components/relationship-profile";

export {
  FiCardCreationPage,
  FiCardCreationShell,
  FiCardCreationHeader,
  FiCardCreationStepProgress,
  FiCardCreationRecipientStep,
  FiCardCreationEmptyState,
  FiCardCreationOccasionStep,
  FiCardCreationGenerateStep,
  FiCardCreationDraftsStep,
  FiCardCreationReviewStep,
  FiCardCreationConfirmStep,
} from "@/app/components/card-creation";

export {
  FiRecipientsPage,
  FiRecipientsHeader,
  FiRecipientsToolbar,
  FiRecipientsPersonCard,
  FiRecipientsGroupSection,
  FiRecipientsComingUp,
  FiRecipientsEmptyState,
  FiRecipientsNoResults,
  FiRecipientsArchivedSection,
  FiRecipientsLoadingState,
  FiRecipientsErrorState,
} from "@/app/components/recipients";

export { FiRecipientManagementPage } from "@/app/components/recipient-management";

export {
  FiAutopilotPage,
  FiAutopilotStatusHero,
  FiAutopilotCoverageSummaryPanel,
  FiAutopilotUpcomingAutomated,
  FiAutopilotRecommendations,
  FiAutopilotRecentActivity,
  FiAutopilotInsights,
  FiAutopilotManagement,
  FiAutopilotHelpSection,
  FiAutopilotLoadingState,
  FiAutopilotErrorState,
  FiAutopilotOfflineState,
  FiAutopilotEmptyState,
} from "@/app/components/autopilot";

export { FiAccountSettingsPage } from "@/app/components/account-settings";

export { FiRelationshipPreferencesPage } from "@/app/components/relationship-preferences";

export {
  FiSettingsEmptyState,
  FiSettingsErrorState,
  FiSettingsInlineLoading,
  FiSettingsNav,
  FiSettingsNavLoading,
  FiSettingsPageLoading,
  FiSettingsShell,
} from "@/app/components/settings";

export {
  FiOnboardingPage,
  FiOnboardingWelcome,
  FiOnboardingLegacyFlow,
} from "@/app/components/onboarding";

export {
  FiAuthPage,
  FiAuthShell,
  FiAuthPitch,
  FiLoginForm,
  FiSignupForm,
  FiAuthRecoveryPanels,
  FiAuthPasswordField,
  FiAuthModeToggle,
} from "@/app/components/auth";
export type { FiAuthPageProps } from "@/app/components/auth";

export {
  FiBillingPage,
  FiSubscribePage,
  FiCheckoutSuccessPage,
  FiBillingSections,
  FiPlanCard,
  FiPlanGrid,
} from "@/app/components/billing";

export {
  FiAdminPage,
  FiAdminShell,
  FiAdminDashboardPanel,
  FiAdminTools,
  FiAdminIllustrationLibrary,
  FiAdminCopyManagement,
  FiAdminLegacyContent,
} from "@/app/components/admin";

export {
  FiAiAdminPage,
  FiAutomationAdminPage,
  FiAiAdminPanel,
  FiAutomationAdminPanel,
} from "@/app/components/ai-automation";
