import {randomUUID} from 'node:crypto';import {and,eq,inArray} from 'drizzle-orm';
import {relationshipHypothesesTable,relationshipHypothesisVersionsTable,relationshipHypothesisHeadsTable,relationshipHypothesisEvidenceTable,relationshipHypothesisActionsTable,relationshipObservationVersionsTable,relationshipInterpretationsTable,relationshipInterpretationDependenciesTable,relationshipInterpretationRevisionsTable} from '@workspace/db/schema';
import {currentObservationVersions} from './versioned-understanding';import {deriveCommunicationPreferenceHypothesis,EVOLVING_UNDERSTANDING_POLICY,EVOLVING_UNDERSTANDING_POLICY_VERSION,type HypothesisEvidence} from '../brain/evolving-understanding';import type {UnderstandingDatabase} from './versioned-understanding-repository';
const scopeWhere=(table:any,scope:{userId:string;recipientId:string})=>and(eq(table.userId,scope.userId),eq(table.recipientId,scope.recipientId));

export async function recomputeEvolvingUnderstanding(db:UnderstandingDatabase,scope:{userId:string;recipientId:string}){
 const [observations,interpretations,dependencies,revisions,hypotheses,heads]=await Promise.all([db.select().from(relationshipObservationVersionsTable).where(scopeWhere(relationshipObservationVersionsTable,scope)),db.select().from(relationshipInterpretationsTable).where(scopeWhere(relationshipInterpretationsTable,scope)),db.select().from(relationshipInterpretationDependenciesTable),db.select().from(relationshipInterpretationRevisionsTable).where(scopeWhere(relationshipInterpretationRevisionsTable,scope)),db.select().from(relationshipHypothesesTable).where(scopeWhere(relationshipHypothesesTable,scope)),db.select().from(relationshipHypothesisHeadsTable).where(scopeWhere(relationshipHypothesisHeadsTable,scope))]);
 const active=currentObservationVersions(observations,scope).filter(v=>v.lifecycleState==='active'),activeIds=new Set(active.map(v=>v.id));const evidence:HypothesisEvidence[]=active.map(v=>({observationVersionId:v.id,text:v.text,sourceKind:v.sourceKind,semanticClassification:v.semanticClassification}));
 for(const interpretation of interpretations.filter(i=>i.lifecycleState==='active'&&!i.endorsementWithdrawnAt)){const revision=revisions.find(r=>r.interpretationId===interpretation.id&&r.revision===interpretation.revision&&r.lifecycleState==='active'&&!r.endorsementWithdrawnAt);const pinned=dependencies.filter(d=>d.interpretationId===interpretation.id).map(d=>d.observationVersionId);if(revision&&pinned.length&&pinned.every(id=>activeIds.has(id)))for(const observationVersionId of pinned)evidence.push({observationVersionId,interpretationId:interpretation.id,interpretationRevision:revision.revision,text:revision.text});}
 const judgment=deriveCommunicationPreferenceHypothesis(evidence),existing=hypotheses.find(h=>h.family===EVOLVING_UNDERSTANDING_POLICY),head=existing?heads.find(h=>h.hypothesisId===existing.id):undefined;
 const history=existing?await db.select().from(relationshipHypothesisVersionsTable).where(eq(relationshipHypothesisVersionsTable.hypothesisId,existing.id)):[],current=head?history.find(v=>v.id===head.currentVersionId):undefined;
 const historyLinks=history.length?await db.select().from(relationshipHypothesisEvidenceTable).where(inArray(relationshipHypothesisEvidenceTable.hypothesisVersionId,history.map(v=>v.id))):[];
 const lifecycleState=judgment?'active':'retired',fingerprint=judgment?.fingerprint??'no-current-evidence';if(current&&current.evidenceFingerprint===fingerprint&&current.lifecycleState===lifecycleState)return current;if(!existing&&!judgment)return null;
 if(current?.lifecycleState==='retired'&&judgment){const signature=(versionId:string|null)=>{const row=observations.find(value=>value.id===versionId);return row?`${row.sourceRecordId??row.id}:${row.text.trim().toLocaleLowerCase()}`:null;};const previouslyConsumed=new Set(historyLinks.filter(link=>link.polarity==='support').map(link=>signature(link.observationVersionId)).filter(Boolean));if(!judgment.support.some(item=>!previouslyConsumed.has(signature(item.observationVersionId))))return current;}
 const hypothesisId=existing?.id??randomUUID(),version=(current?.version??0)+1,id=randomUUID(),now=new Date();if(!existing)await db.insert(relationshipHypothesesTable).values({id:hypothesisId,...scope,family:EVOLVING_UNDERSTANDING_POLICY,subjectKey:judgment!.subjectKey,createdAt:now});
 await db.insert(relationshipHypothesisVersionsTable).values({id,hypothesisId,...scope,version,lifecycleState,evidenceState:judgment?.evidenceState??'unknown',policy:EVOLVING_UNDERSTANDING_POLICY,policyVersion:EVOLVING_UNDERSTANDING_POLICY_VERSION,rationale:judgment?.rationale??'No current valid evidence remains.',explanation:judgment?.explanation??'The prior hypothesis was retired because its exact source support is no longer current and active.',uncertainty:judgment?.uncertainty??'No current support.',confidence:null,supportCount:judgment?.support.length??0,conflictCount:judgment?.conflict.length??0,evidenceFingerprint:fingerprint,supersedesVersionId:current?.id??null,generatedAt:now});
 if(judgment?.evidenceLinks.length)await db.insert(relationshipHypothesisEvidenceTable).values(judgment.evidenceLinks.map(link=>({hypothesisVersionId:id,observationVersionId:link.observationVersionId,interpretationId:link.interpretationId??null,interpretationRevision:link.interpretationRevision??null,polarity:link.polarity})));
 if(head){const changed=await db.update(relationshipHypothesisHeadsTable).set({currentVersionId:id,revision:head.revision+1,updatedAt:now}).where(and(eq(relationshipHypothesisHeadsTable.hypothesisId,hypothesisId),eq(relationshipHypothesisHeadsTable.currentVersionId,current!.id),eq(relationshipHypothesisHeadsTable.revision,head.revision))).returning();if(!changed.length)throw Error('STALE_HYPOTHESIS_HEAD');}else await db.insert(relationshipHypothesisHeadsTable).values({hypothesisId,...scope,currentVersionId:id,revision:1,updatedAt:now});return{id,hypothesisId,version,lifecycleState};
}

export async function loadActiveHypotheses(db:UnderstandingDatabase,scope:{userId:string;recipientId:string}){const heads=await db.select().from(relationshipHypothesisHeadsTable).where(scopeWhere(relationshipHypothesisHeadsTable,scope));if(!heads.length)return[];const versions=await db.select().from(relationshipHypothesisVersionsTable).where(inArray(relationshipHypothesisVersionsTable.id,heads.map(h=>h.currentVersionId)));const links=await db.select().from(relationshipHypothesisEvidenceTable).where(inArray(relationshipHypothesisEvidenceTable.hypothesisVersionId,versions.map(v=>v.id)));const observations=await db.select().from(relationshipObservationVersionsTable).where(scopeWhere(relationshipObservationVersionsTable,scope));const currentIds=new Set(currentObservationVersions(observations,scope).filter(v=>v.lifecycleState==='active').map(v=>v.id));const [revisions,interpretations,actions]=await Promise.all([db.select().from(relationshipInterpretationRevisionsTable).where(scopeWhere(relationshipInterpretationRevisionsTable,scope)),db.select().from(relationshipInterpretationsTable).where(scopeWhere(relationshipInterpretationsTable,scope)),db.select().from(relationshipHypothesisActionsTable).where(scopeWhere(relationshipHypothesisActionsTable,scope))]);return versions.filter(v=>v.lifecycleState==='active').filter(v=>{const latest=actions.filter(a=>a.hypothesisId===v.hypothesisId).sort((a,b)=>b.newRevision-a.newRevision)[0];if(latest&&['disagreed','withdrawn'].includes(latest.responseState))return false;const evidence=links.filter(l=>l.hypothesisVersionId===v.id);return evidence.length>0&&evidence.every(link=>link.observationVersionId&&currentIds.has(link.observationVersionId)&&(!link.interpretationId||interpretations.some(i=>i.id===link.interpretationId&&i.revision===link.interpretationRevision&&i.lifecycleState==='active'&&!i.endorsementWithdrawnAt)&&revisions.some(r=>r.interpretationId===link.interpretationId&&r.revision===link.interpretationRevision&&r.lifecycleState==='active'&&!r.endorsementWithdrawnAt)));}).map(v=>({...v,semanticClassification:'uncertain_hypothesis' as const,confidence:null,evidence:links.filter(l=>l.hypothesisVersionId===v.id)}));}

export async function changeHypothesis(db:UnderstandingDatabase,scope:{userId:string;recipientId:string},hypothesisId:string,action:string,expectedRevision:number,operationId:string){const [duplicate]=await db.select().from(relationshipHypothesisActionsTable).where(and(scopeWhere(relationshipHypothesisActionsTable,scope),eq(relationshipHypothesisActionsTable.operationId,operationId))).limit(1);if(duplicate){if(duplicate.hypothesisId!==hypothesisId||duplicate.action!==action||duplicate.expectedRevision!==expectedRevision)throw Error('OPERATION_MISMATCH');return duplicate;}
 const [head]=await db.select().from(relationshipHypothesisHeadsTable).where(and(eq(relationshipHypothesisHeadsTable.hypothesisId,hypothesisId),scopeWhere(relationshipHypothesisHeadsTable,scope))).limit(1);if(!head)throw Error('NOT_FOUND');if(head.revision!==expectedRevision)throw Error('STALE');if(!['confirm','disagree','withdraw','reverse'].includes(action))throw Error('UNSUPPORTED');
 const [current]=await db.select().from(relationshipHypothesisVersionsTable).where(and(eq(relationshipHypothesisVersionsTable.id,head.currentVersionId),scopeWhere(relationshipHypothesisVersionsTable,scope))).limit(1);if(!current||current.lifecycleState!=='active')throw Error('INVALID_EVIDENCE');const actions=await db.select().from(relationshipHypothesisActionsTable).where(and(scopeWhere(relationshipHypothesisActionsTable,scope),eq(relationshipHypothesisActionsTable.hypothesisId,hypothesisId)));const latest=[...actions].sort((a,b)=>b.newRevision-a.newRevision)[0],prior=latest?.hypothesisVersionId===current.id?latest.responseState:['disagreed','withdrawn'].includes(latest?.responseState??'')?latest!.responseState:'none';let responseState:string;if(action==='confirm'||action==='disagree'){if(prior!=='none')throw Error('UNSUPPORTED');responseState=action==='confirm'?'confirmed':'disagreed';}else if(action==='withdraw'){if(!['confirmed','disagreed'].includes(prior))throw Error('UNSUPPORTED');responseState='withdrawn';}else{if(!['disagreed','withdrawn'].includes(prior)||current.evidenceState==='unknown')throw Error('UNSUPPORTED');responseState='none';}
 const newRevision=head.revision+1,changed=await db.update(relationshipHypothesisHeadsTable).set({revision:newRevision,updatedAt:new Date()}).where(and(eq(relationshipHypothesisHeadsTable.hypothesisId,hypothesisId),eq(relationshipHypothesisHeadsTable.currentVersionId,current.id),eq(relationshipHypothesisHeadsTable.revision,expectedRevision))).returning();if(!changed.length)throw Error('STALE');const row={id:randomUUID(),hypothesisId,hypothesisVersionId:current.id,...scope,action,responseState,operationId,expectedRevision,newRevision,actorUserId:scope.userId,actedAt:new Date()};await db.insert(relationshipHypothesisActionsTable).values(row);return row;}
