uploads = []
outputs = []

[[generated]]
id = "hypLLZACBFDfw-6y1sr7z"
uri = "file://artifacts/fi-forgot/public/hero-ai.png"
type = "image"
title = "confused man forgot mothers day hero"

[[generated]]
id = "p1240Gj9d-ohhjnUA-JJS"
uri = "file://artifacts/fi-forgot/public/hero-bg.png"
type = "image"
title = "navy hero background man forgot mothers day"

[[generated]]
id = "FM1DQvu0JWU6yQPoguR9d"
uri = "file://attached_assets/generated_images/photorealistic_photo_of_a_1bee.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6Qz7IXuP2ZbCDley5PWRR"
uri = "file://attached_assets/generated_images/simple_illustrated_icon_on_9f1a.png"
type = "image"
title = "generated_image"

[[generated]]
id = "k7IxK4T-s9ASpqCya8bw2"
uri = "file://attached_assets/generated_images/simple_illustrated_icon_on_000b.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yFvs1twhBUWPSda2XUSyC"
uri = "file://attached_assets/generated_images/simple_illustrated_icon_on_64eb.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nl5Wvt_BaYcK-Jm363TjJ"
uri = "file://attached_assets/generated_images/simple_illustrated_icon_on_1e62.png"
type = "image"
title = "generated_image"

[[generated]]
id = "s5K_ZYgROQrQe3O42HfwO"
uri = "file://attached_assets/generated_images/simple_illustrated_icon_on_a9f0.png"
type = "image"
title = "generated_image"
