import { Router, type IRouter } from "express";
import healthRouter from "./health";
import stripeRouter from "./stripe";
import generateCardRouter from "./generate-card";
import editCardRouter from "./edit-card";
import adminRouter from "./admin";
import approvalRouter from "./approval";
import demoEmailRouter from "./demo-email";
import cardProxyRouter from "./card-proxy";
import cardImageRouter from "./card-image";
import demoPreviewRouter from "./demo-preview";
import refineMessageRouter from "./refine-message";
import businessCardMessageRouter from "./business-card-message";
import sampleCardsRouter from "./sample-cards";
import businessClientsRouter from "./business-clients";
import businessSettingsRouter from "./business-settings";
import handwryttenFontsRouter from "./handwrytten-fonts";
import businessApprovalRouter from "./business-approval";
import businessSchedulerTriggerRouter from "./business-scheduler-trigger"; // also mounts /business-cards/generate
import cardLibraryRouter from "./card-library";
import personalCardsRouter from "./personal-cards";
import personalRecipientsRouter from "./personal-recipients";
import cardPreviewRouter from "./card-preview";
import v2RecipientsRouter from "./v2-recipients";
import v2GenerateCardRouter from "./v2-generate-card";
import personalHistoryRouter from "./personal-history";
import debugRouter from "./debug";
import brainDebugRouter from "../brain/debug/brainDebugRoute";
import browniePointsRouter from "./brownie-points";
import v2RecipientHealthRouter from "./v2-recipient-health";
import v2DashboardBrainRouter from "./v2-dashboard-brain";
import v2NotificationsRouter from "./v2-notifications";
import v2ConciergeRouter from "./v2-concierge";

const router: IRouter = Router();

router.use(healthRouter);
router.use(generateCardRouter);
router.use(editCardRouter);
router.use(adminRouter);
router.use(approvalRouter);
router.use(demoEmailRouter);
router.use(cardProxyRouter);
router.use(cardImageRouter);
router.use(demoPreviewRouter);
router.use(refineMessageRouter);
router.use(businessCardMessageRouter);
router.use(sampleCardsRouter);
router.use(businessClientsRouter);
router.use(businessSettingsRouter);
router.use(handwryttenFontsRouter);
router.use(businessApprovalRouter);
router.use(businessSchedulerTriggerRouter);
router.use(cardLibraryRouter);
router.use(personalCardsRouter);
router.use(personalRecipientsRouter);
router.use(cardPreviewRouter);
router.use(v2RecipientHealthRouter);
router.use(v2DashboardBrainRouter);
router.use(v2NotificationsRouter);
router.use(v2ConciergeRouter);
router.use(v2RecipientsRouter);
router.use(v2GenerateCardRouter);
router.use(personalHistoryRouter);
router.use(debugRouter);
router.use(brainDebugRouter);
router.use(browniePointsRouter);
router.use(stripeRouter);

export default router;
