import { Router, type IRouter } from "express";
import healthRouter from "./health";
import generateCardRouter from "./generate-card";
import editCardRouter from "./edit-card";
import adminRouter from "./admin";
import approvalRouter from "./approval";
import demoEmailRouter from "./demo-email";
import cardProxyRouter from "./card-proxy";
import cardImageRouter from "./card-image";
import demoPreviewRouter from "./demo-preview";
import refineMessageRouter from "./refine-message";
import businessCardMessageRouter from "./business-card-message";
import sampleCardsRouter from "./sample-cards";
import businessClientsRouter from "./business-clients";
import businessSettingsRouter from "./business-settings";
import handwryttenFontsRouter from "./handwrytten-fonts";
import businessApprovalRouter from "./business-approval";
import businessSchedulerTriggerRouter from "./business-scheduler-trigger";

const router: IRouter = Router();

router.use(healthRouter);
router.use(generateCardRouter);
router.use(editCardRouter);
router.use(adminRouter);
router.use(approvalRouter);
router.use(demoEmailRouter);
router.use(cardProxyRouter);
router.use(cardImageRouter);
router.use(demoPreviewRouter);
router.use(refineMessageRouter);
router.use(businessCardMessageRouter);
router.use(sampleCardsRouter);
router.use(businessClientsRouter);
router.use(businessSettingsRouter);
router.use(handwryttenFontsRouter);
router.use(businessApprovalRouter);
router.use(businessSchedulerTriggerRouter);

export default router;
