export const ROUTE_PATHS = {
  home: "/",
  login: "/login",
  signup: "/signup",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  recipients: "/recipients",
  recipientProfile: "/recipients/:id",
  relationship: "/relationship/:id",
  briefing: "/briefings/:recipientId/:event",
  briefingDetail: "/briefings/:recipientId/:event/:briefingId",
  cardsGenerate: "/cards/generate",
  cardsReview: "/cards/review",
  browniePoints: "/brownie-points",
  people: "/people",
  moments: "/moments",
  autopilot: "/autopilot",
  quickCard: "/quick-card",
  settingsReminders: "/settings/reminders",
  settingsAccount: "/settings/account",
  settingsRelationship: "/settings/relationship",
  settingsBilling: "/settings/billing",
  notifications: "/notifications",
  search: "/search",
  concierge: "/concierge",
  systemVerification: "/system-verification",
  brainPlayground: "/brain-playground",
  launchReadiness: "/launch-readiness",
  admin: "/admin",
  try: "/try",
  tryLegacy: "/v2",
  subscribe: "/subscribe",
  checkoutSuccess: "/checkout/success",
  demo: "/demo/:id",
  business: "/business",
  businessDemo: "/business-demo",
  businessSampleCards: "/business/sample-cards",
  businessSignup: "/business/signup",
  businessLogin: "/business/login",
  businessCreateWorkspace: "/business/create-workspace",
  businessDashboard: "/business/dashboard",
  businessApprove: "/business/approve/:token",
  cardPreview: "/preview/:token",
  error: "/error",
} as const;

export const ROUTE_REDIRECTS = {
  browniePointsToDashboard: {
    from: ROUTE_PATHS.browniePoints,
    to: ROUTE_PATHS.dashboard,
  },
  tryLegacyToTry: {
    from: ROUTE_PATHS.tryLegacy,
    to: ROUTE_PATHS.try,
  },
  recipientsToPeople: {
    from: ROUTE_PATHS.recipients,
    to: ROUTE_PATHS.people,
  },
} as const;

/** Paths where the floating try CTA should stay hidden. */
export const HIDE_TRY_BUTTON_ON = [
  ROUTE_PATHS.home,
  ROUTE_PATHS.login,
  ROUTE_PATHS.signup,
  ROUTE_PATHS.try,
  ROUTE_PATHS.tryLegacy,
  ROUTE_PATHS.subscribe,
  "/checkout",
  "/demo",
  ROUTE_PATHS.dashboard,
  "/recipients",
  ROUTE_PATHS.onboarding,
  "/cards",
  "/settings",
  ROUTE_PATHS.notifications,
  ROUTE_PATHS.search,
  ROUTE_PATHS.concierge,
  ROUTE_PATHS.systemVerification,
  ROUTE_PATHS.brainPlayground,
  ROUTE_PATHS.launchReadiness,
  ROUTE_PATHS.admin,
  "/briefings",
  "/business",
  ROUTE_PATHS.businessDemo,
  ROUTE_PATHS.browniePoints,
  ROUTE_PATHS.people,
  ROUTE_PATHS.moments,
  ROUTE_PATHS.autopilot,
  ROUTE_PATHS.quickCard,
  "/relationship",
] as const;
