import { runAssignmentTests } from "./assignment.test.js";
import { runProviderContractTests } from "./provider-contract.test.js";
import { runEventNormalizationTests } from "./events.test.js";
import { runGitEvidenceTests } from "./git-evidence.test.js";
import { runPathNormalizationTests } from "./path-normalize.test.js";
import { runHookDecisionTests, runHookParserTests } from "./hook-policy.test.js";
import { runResultTests } from "./result.test.js";
import { runAdapterNegativeTests, runFixtureIntegrationTests } from "./fixture-integration.test.js";
import { runEngineeringStoreTests } from "./engineering-store.test.js";
import { runVerifierPreparationTests } from "./verifier-preparation.test.js";
import { runVerifierDispatchTests } from "./verifier-dispatch.test.js";
import { runVerifierRoutingTests } from "./verifier-routing.test.js";
import { runVerifierTrustBoundaryTests } from "./verifier-trust-boundary.test.js";
import { runVerificationDecisionTests } from "./verification-decision.test.js";
import { runPostDecisionActionTests } from "./post-decision-action.test.js";
import { runPostDecisionExecutionTests } from "./post-decision-execution.test.js";
import { liveCursorReport, runLiveCursorIntegrationTest } from "./live-cursor.integration.test.js";
import { runCodexProviderTests } from "./codex-provider.test.js";
import { runCodexAppServerTransportTests } from "./codex-app-server-transport.test.js";
import { failed, reportAndExit } from "./harness.js";
import { runIsolatedWorkspaceTests } from "./isolated-workspace.test.js";

async function main(): Promise<void> {
  runAssignmentTests();
  await runProviderContractTests();
  await runCodexAppServerTransportTests();
  await runCodexProviderTests();
  runEventNormalizationTests();
  await runGitEvidenceTests();
  runPathNormalizationTests();
  runHookDecisionTests();
  runHookParserTests();
  runResultTests();
  await runFixtureIntegrationTests();
  await runIsolatedWorkspaceTests();
  await runAdapterNegativeTests();
  await runEngineeringStoreTests();
  await runVerifierPreparationTests();
  await runVerifierDispatchTests();
  await runVerifierRoutingTests();
  await runVerifierTrustBoundaryTests();
  await runVerificationDecisionTests();
  await runPostDecisionActionTests();
  await runPostDecisionExecutionTests();
  await runLiveCursorIntegrationTest();
  console.log("\nLive Cursor report:", JSON.stringify(liveCursorReport, null, 2));
  if (failed > 0) reportAndExit();
  reportAndExit();
}

await main();
