import { existsSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { resolve } from "node:path";
import {createServer} from 'node:net';
// @ts-ignore Explicit runtime extension.
import {stopManagedProcess} from './process-lifecycle.ts';
// @ts-ignore Node built-in type stripping requires runtime extensions.
import { assertExecutionGates, buildPlan, sha256, type GateInput, type PlannedCommand, TARGET } from "./plan.ts";
export type TargetInspection={resolvedPgdata:string;targetExists:boolean;parentApproved:boolean;postgresMajor:number;sqlHashesVerified:boolean;baselineHashVerified:boolean;catalogState:"absent"|"unexpected"};
export interface ExecutionAdapter{inspect(root:string):TargetInspection;run(command:PlannedCommand):string|Promise<string>;recover?(completed:readonly string[]):void|Promise<void>;}
export function assertOwnedCleanupEvidence(e:{resolvedPgdata:string;marker:string;postgresMajor:string;postgresStopped:boolean;portReleased:boolean}){if(e.resolvedPgdata!==TARGET.pgdata||e.marker!=="fi-forgot-brain-qualification-owned-v1\n"||e.postgresMajor.trim()!=="16"||!e.postgresStopped||!e.portReleased)throw new Error("FAIL_CLOSED: independently observed cleanup evidence mismatch");}
export async function executeFutureQualification(input:GateInput,adapter:ExecutionAdapter,root=resolve(import.meta.dirname,"../../..")){if(assertExecutionGates(input)!=="execution-authorized")return;const i=adapter.inspect(root);if(i.resolvedPgdata!==TARGET.pgdata||i.targetExists||!i.parentApproved||i.postgresMajor!==16||!i.sqlHashesVerified||!i.baselineHashVerified||i.catalogState!=="absent")throw new Error("FAIL_CLOSED: observed runtime, artifact hashes, or disposable target state did not match");const completed:string[]=[];try{for(const command of buildPlan(root)){const output=await adapter.run(command);if(command.phase==="identity"&&!output.includes(`${TARGET.database}|${TARGET.role}|16`))throw new Error("FAIL_CLOSED: observed PostgreSQL identity mismatch");completed.push(command.phase);}}catch(error){await adapter.recover?.(completed);throw error;}}
export function createSystemExecutionAdapter():ExecutionAdapter{
  let api:ChildProcess|null=null;
  const secret=(name:string)=>{const value=process.env[name];if(!value||value.length<20)throw new Error(`FAIL_CLOSED: process-only credential ${name} missing`);return value;};
  return {
    inspect(root){const parent=TARGET.pgdata.slice(0,TARGET.pgdata.lastIndexOf("/")),manifest=JSON.parse(readFileSync(resolve(root,"docs/brain-qualification-preparation/migration-manifest.json"),"utf8"));const version=spawnSync("postgres",["--version"],{encoding:"utf8",shell:false});return{resolvedPgdata:TARGET.pgdata,targetExists:existsSync(TARGET.pgdata),parentApproved:existsSync(parent)&&realpathSync(parent).replaceAll("\\","/")===parent,postgresMajor:Number(/(\d+)\./.exec(version.stdout)?.[1]),sqlHashesVerified:manifest.files.every((x:{file:string;sha256:string})=>sha256(resolve(root,"lib/db/src/schema",x.file))===x.sha256),baselineHashVerified:sha256(resolve(root,"docs/brain-qualification-preparation/bootstrap/0000-current.sql"))===manifest.freshBootstrap.sha256,catalogState:"absent"};},
    async run(c){
      if(c.program==="@qualification/initialize-cluster"){const r=spawnSync("initdb",["--pgdata",TARGET.pgdata,"--username",TARGET.adminRole,"--pwfile=-","--auth-local","scram-sha-256","--auth-host","scram-sha-256"],{input:`${secret("BRAIN_QUALIFICATION_ADMIN_PASSWORD")}\n`,stdio:["pipe","inherit","inherit"],shell:false});if(r.status!==0)throw new Error("initialize-cluster failed");return"";}
      if(c.program==="@qualification/mark-owned-cluster"){if(!existsSync(TARGET.pgdata))throw new Error("initialized cluster absent");writeFileSync(`${TARGET.pgdata}/.fi-forgot-brain-qualification-owned`,"fi-forgot-brain-qualification-owned-v1\n",{flag:"wx"});return"";}
      if(c.program==="@qualification/create-role"){const password=secret("BRAIN_QUALIFICATION_APP_PASSWORD"),r=spawnSync("createuser",["--host",TARGET.host,"--port",String(TARGET.port),"--username",TARGET.adminRole,"--pwprompt","--no-createdb","--no-createrole","--no-superuser",TARGET.role],{input:`${password}\n${password}\n`,stdio:["pipe","inherit","inherit"],shell:false});if(r.status!==0)throw new Error("create-role failed");return"";}
      const qualifiedEnv=(includeAdmin=false)=>({...process.env,...c.env,DATABASE_URL:`postgresql://${TARGET.role}:${encodeURIComponent(secret("BRAIN_QUALIFICATION_APP_PASSWORD"))}@${TARGET.host}:${TARGET.port}/${TARGET.database}`,...(includeAdmin?{BRAIN_QUALIFICATION_ADMIN_DATABASE_URL:`postgresql://${TARGET.adminRole}:${encodeURIComponent(secret("BRAIN_QUALIFICATION_ADMIN_PASSWORD"))}@${TARGET.host}:${TARGET.port}/postgres`}:{BRAIN_QUALIFICATION_ADMIN_DATABASE_URL:undefined})});
      if(c.process==="capture"){if(api)throw new Error("API process already captured");api=spawn(c.program,c.args,{cwd:resolve(import.meta.dirname,"../../.."),env:qualifiedEnv(),stdio:["ignore","inherit","inherit","ipc"],shell:false});if(!api.pid)throw new Error("API process did not start");return"";}
      if(c.process==="stop-captured"){
        if(!api?.pid)throw new Error('No qualified API process captured');
        const child=api;
        await stopManagedProcess({
          requestGracefulStop(){if(child.connected)child.send('brain-qualification-stop');else child.kill('SIGTERM');},
          waitForExit(timeoutMs){return new Promise(resolve=>{if(child.exitCode!==null||child.signalCode!==null){resolve(true);return;}const finish=()=>{clearTimeout(timer);resolve(true);};const timer=setTimeout(()=>{child.off('exit',finish);resolve(false);},timeoutMs);child.once('exit',finish);});},
          forceStop(){child.kill('SIGKILL');},
          assertPortReleased(){return new Promise((resolve,reject)=>{const probe=createServer();probe.once('error',()=>reject(new Error('FAIL_CLOSED: API port remains occupied')));probe.listen(TARGET.apiPort,TARGET.host,()=>probe.close(error=>error?reject(error):resolve()));});}
        });
        api=null;return '';
      }
      const needsApp=c.phase==="fixtures"||c.phase.startsWith("assert")||c.phase.startsWith("wait-api"),r=spawnSync(c.program,c.args,{cwd:resolve(import.meta.dirname,"../../.."),env:needsApp?qualifiedEnv(c.phase==="fixtures"):{...process.env,...c.env},encoding:"utf8",stdio:c.phase==="identity"?"pipe":"inherit",shell:false});if(r.error||r.status!==0)throw new Error(`qualification phase failed: ${c.phase}`);return String(r.stdout??"").replace(/\s+/g,"");
    },
    async recover(completed){if(api?.pid){const child=api;await stopManagedProcess({requestGracefulStop(){if(child.connected)child.send("brain-qualification-stop");else child.kill("SIGTERM");},waitForExit(timeoutMs){return new Promise(resolveExit=>{if(child.exitCode!==null||child.signalCode!==null){resolveExit(true);return;}const finish=()=>{clearTimeout(timer);resolveExit(true);},timer=setTimeout(()=>{child.off("exit",finish);resolveExit(false);},timeoutMs);child.once("exit",finish);});},forceStop(){child.kill("SIGKILL");},assertPortReleased(){return new Promise((resolvePort,reject)=>{const probe=createServer();probe.once("error",()=>reject(new Error("FAIL_CLOSED: API port remains occupied")));probe.listen(TARGET.apiPort,TARGET.host,()=>probe.close(error=>error?reject(error):resolvePort()));});}});api=null;}const marker=`${TARGET.pgdata}/.fi-forgot-brain-qualification-owned`;if(!completed.includes("mark-owned-cluster")||!existsSync(marker))throw new Error("FAIL_CLOSED: unowned recovery target");const stopped=!completed.includes("start-postgres")||spawnSync("pg_ctl",["--pgdata",TARGET.pgdata,"stop","--mode","fast","--wait","--timeout","10"],{shell:false,stdio:"inherit"}).status===0;const portReleased=await new Promise<boolean>(resolvePort=>{const probe=createServer();probe.once("error",()=>resolvePort(false));probe.listen(TARGET.port,TARGET.host,()=>probe.close(error=>resolvePort(!error)));});assertOwnedCleanupEvidence({resolvedPgdata:realpathSync(TARGET.pgdata).replaceAll("\\","/"),marker:readFileSync(marker,"utf8"),postgresMajor:readFileSync(`${TARGET.pgdata}/PG_VERSION`,"utf8"),postgresStopped:stopped,portReleased});rmSync(TARGET.pgdata,{recursive:true,force:false});},
  };
}
