// @ts-ignore Native runtime extension.
import './test-postgres-recovery.ts';
// @ts-ignore Native runtime extension.
import './test-postgres-identity.ts';
import{existsSync,readFileSync,realpathSync,unlinkSync,rmdirSync}from"node:fs";
import{tmpdir}from"node:os";
import assert from"node:assert/strict";
// @ts-ignore Native runtime extension.
import './test-postgres-restart.ts';
// @ts-ignore Node built-in type stripping requires runtime extensions.
import{subprocessFailureMetadata,maySkipPreInitializationRecovery,assertPrivateCredentialBase,assertOwnedCleanupEvidence,createSystemExecutionAdapter,executeFutureQualification,type ExecutionAdapter}from"./execution.ts";
// @ts-ignore Node built-in type stripping requires runtime extensions.
import{buildPlan,EXACT_AUTHORIZATION,TARGET,type PlannedCommand}from"./plan.ts";
const exact={execute:true,syntheticRunDate:"2031-04-05",osBoundary:"reviewed-loopback-only",authorization:EXACT_AUTHORIZATION,host:TARGET.host,port:TARGET.port,database:TARGET.database,role:TARGET.role,pgdata:TARGET.pgdata,postgresMajor:16,disposable:true,catalogApproved:true,hashesApproved:true,credentialEnv:"PGPASSWORD"};
const observed=()=>({resolvedPgdata:TARGET.pgdata,targetExists:false,parentApproved:true,postgresMajor:16,sqlHashesVerified:true,baselineHashVerified:true,catalogState:"absent"as const});
const calls:PlannedCommand[]=[];let recovered:string[]|null=null;const fake:ExecutionAdapter={inspect:observed,run:c=>{calls.push(c);return c.phase==="identity"?`${TARGET.database}|${TARGET.role}|16`:"";},recover:x=>{recovered=[...x]}};
await executeFutureQualification(exact,fake);const phases=calls.map(x=>x.phase);for(const phase of["initialize-cluster","mark-owned-cluster","start-postgres","create-role","create-database","identity","fresh-baseline","fixtures","start-api","wait-api","assert","stop-api","restart-api","wait-api-after-restart","assert-after-restart","stop-api-final","stop-postgres"])assert.ok(phases.includes(phase),`missing ${phase}`);
for(const c of calls){assert.ok(c.program);assert.ok(Array.isArray(c.args));assert.ok(!c.args.some(x=>/<[^>]+>/.test(x)));}
let untouched=0;await executeFutureQualification({execute:false},{inspect(){untouched++;throw 0},run(){untouched++;return""}});assert.equal(untouched,0);
for(const denied of[{...exact,authorization:"wrong"},{...exact,hashesApproved:false},{...exact,catalogApproved:false},{...exact,disposable:false},{...exact,host:"localhost"}])await assert.rejects(()=>executeFutureQualification(denied,fake),/FAIL_CLOSED/);
for(const bad of[{...observed(),sqlHashesVerified:false},{...observed(),baselineHashVerified:false},{...observed(),targetExists:true},{...observed(),postgresMajor:15}])await assert.rejects(()=>executeFutureQualification(exact,{...fake,inspect:()=>bad}),/FAIL_CLOSED/);
const failing:ExecutionAdapter={inspect:observed,run:c=>{if(c.phase==="fixtures")throw new Error("fixture failure");return c.phase==="identity"?`${TARGET.database}|${TARGET.role}|16`:"";},recover:x=>{recovered=[...x]}};await assert.rejects(()=>executeFutureQualification(exact,failing),/fixture failure/);assert.ok(Array.isArray(recovered));const receipt=recovered as unknown as string[];assert.ok(receipt.includes("fresh-baseline"));assert.ok(!receipt.includes("fixtures"));
console.log("future typed execution admission/order/hash/identity/recovery tests: PASS (fake adapter only)");
assert.doesNotThrow(()=>assertOwnedCleanupEvidence({resolvedPgdata:TARGET.pgdata,marker:"fi-forgot-brain-qualification-owned-v1\n",postgresMajor:"16\n",postgresStopped:true,portReleased:true}));for(const bad of[{resolvedPgdata:"C:/wrong",marker:"fi-forgot-brain-qualification-owned-v1\n",postgresMajor:"16",postgresStopped:true,portReleased:true},{resolvedPgdata:TARGET.pgdata,marker:"wrong",postgresMajor:"16",postgresStopped:true,portReleased:true},{resolvedPgdata:TARGET.pgdata,marker:"fi-forgot-brain-qualification-owned-v1\n",postgresMajor:"16",postgresStopped:false,portReleased:true}])assert.throws(()=>assertOwnedCleanupEvidence(bad),/FAIL_CLOSED/);

const previous={admin:process.env.BRAIN_QUALIFICATION_ADMIN_PASSWORD,app:process.env.BRAIN_QUALIFICATION_APP_PASSWORD,pg:process.env.PGPASSWORD,url:process.env.DATABASE_URL,adminUrl:process.env.BRAIN_QUALIFICATION_ADMIN_DATABASE_URL};
const adminSecret="admin-secret-qualification-123",appSecret="app-secret-qualification-'456",spawnCalls:any[]=[];
process.env.BRAIN_QUALIFICATION_ADMIN_PASSWORD=adminSecret;process.env.BRAIN_QUALIFICATION_APP_PASSWORD=appSecret;process.env.PGPASSWORD="contaminated";process.env.DATABASE_URL="postgresql://contaminated";process.env.BRAIN_QUALIFICATION_ADMIN_DATABASE_URL="postgresql://contaminated-admin";
try{
 const adapter=createSystemExecutionAdapter({credentialBase:realpathSync(tmpdir()),spawnSync:((program:string,args:string[],options:any)=>{if(program==="initdb"){const file=args[args.indexOf("--pwfile")+1];assert.equal(readFileSync(file,"utf8"),adminSecret+"\n");assert.ok(!JSON.stringify(args).includes(adminSecret));assert.equal(options.input,undefined);assert.equal(options.env.BRAIN_QUALIFICATION_ADMIN_PASSWORD,undefined);}spawnCalls.push({program,args,options});const stdout=args.some(arg=>arg.includes("data_directory"))?`postgres|${TARGET.adminRole}|160015|${TARGET.host}|${TARGET.port}|${TARGET.pgdata}|UTF8\n`:args.some(arg=>arg.includes("select current_database(),current_user,current_setting('server_version_num')"))?`${TARGET.database}|${TARGET.role}|16`:"";return{status:0,stdout,stderr:""};})as any});
 const commands=buildPlan();
 for(const phase of["initialize-cluster","start-postgres","create-role","create-database","identity","fresh-baseline","fixtures","wait-api","assert","browser-workflow"]){await adapter.run(commands.find(command=>command.phase===phase)!);}
 const role=spawnCalls.find(call=>call.options.input?.includes("CREATE ROLE"));assert.equal(role.program,"psql");assert.ok(!role.args.includes("--pwprompt"));assert.ok(!role.args.some((arg:string)=>arg.includes(adminSecret)||arg.includes(appSecret)));assert.equal(role.options.env.PGPASSWORD,adminSecret);assert.match(role.options.input,/app-secret-qualification-''456/);assert.equal(role.options.timeout,15000);
 const pgStart=spawnCalls.find(call=>call.program==='pg_ctl'&&call.args.includes('start'));const log=pgStart.args[pgStart.args.indexOf('--log')+1];assert.ok(log.startsWith(realpathSync(tmpdir())));assert.equal(readFileSync(log,'utf8'),'');assert.deepEqual(pgStart.options.stdio,['ignore','ignore','ignore']);unlinkSync(log);rmdirSync(log.slice(0,Math.max(log.lastIndexOf('/'),log.lastIndexOf('\\'))));
 const createdb=spawnCalls.find(call=>call.program==="createdb");assert.equal(createdb.options.env.PGPASSWORD,adminSecret);
 const appCalls=spawnCalls.filter(call=>call.program!=="createdb"&&call!==role&&call.options.env?.DATABASE_URL);assert.ok(appCalls.length>=3);for(const call of appCalls){assert.equal(call.options.env.BRAIN_QUALIFICATION_ADMIN_PASSWORD,undefined);assert.equal(call.options.env.BRAIN_QUALIFICATION_APP_PASSWORD,undefined);if(!call.args.includes("load"))assert.equal(call.options.env.BRAIN_QUALIFICATION_ADMIN_DATABASE_URL,undefined);assert.ok(!call.args.some((arg:string)=>arg.includes(adminSecret)||arg.includes(appSecret)));}
 const fixture=spawnCalls.find(call=>call.args.includes("load"));assert.equal(fixture.options.env.PGPASSWORD,undefined);assert.match(fixture.options.env.DATABASE_URL,/fi_forgot_brain_qualifier/);assert.equal(new URL(fixture.options.env.BRAIN_QUALIFICATION_ADMIN_DATABASE_URL).username,TARGET.adminRole);
 const initialized=spawnCalls.find(call=>call.program==="initdb");assert.equal(initialized.options.timeout,300000);assert.equal(initialized.args[initialized.args.indexOf("--encoding")+1],"UTF8");assert.ok(!existsSync(initialized.args[initialized.args.indexOf("--pwfile")+1]));
 assert.equal(spawnCalls.find(call=>call.args.some((arg:string)=>arg.endsWith("wait-api.ts"))).options.timeout,90000);
 assert.equal(spawnCalls.find(call=>call.args.includes("assert")).options.timeout,300000);
 let apiEnv:any;const capture=createSystemExecutionAdapter({spawn:((_program:any,_args:any,options:any)=>{apiEnv=options.env;return{pid:123,on(){}};})as any});await capture.run(commands.find(command=>command.phase==="start-api")!);
 assert.equal(apiEnv.BRAIN_QUALIFICATION_ADMIN_DATABASE_URL,undefined);assert.equal(apiEnv.BRAIN_QUALIFICATION_ADMIN_PASSWORD,undefined);assert.equal(apiEnv.PGPASSWORD,undefined);assert.equal(apiEnv.BRAIN_QUALIFICATION_APP_PASSWORD,undefined);
 const failed=createSystemExecutionAdapter({spawnSync:(()=>({status:1,error:new Error(adminSecret),stderr:appSecret}))as any});await assert.rejects(async()=>failed.run(commands.find(command=>command.phase==="create-role")!),(error:unknown)=>!String(error).includes(adminSecret)&&!String(error).includes(appSecret));

 for(const outcome of ["failure","throw"]){let credentialPath="";const broken=createSystemExecutionAdapter({credentialBase:realpathSync(tmpdir()),spawnSync:((program:string,args:string[],options:any)=>{if(program==="icacls")return{status:0};credentialPath=args[args.indexOf("--pwfile")+1];assert.equal(readFileSync(credentialPath,"utf8"),adminSecret+"\n");assert.ok(!JSON.stringify(args).includes(adminSecret));if(outcome==="throw")throw new Error("synthetic spawn failure");return{status:1,stderr:"synthetic failure"};})as any});await assert.rejects(async()=>broken.run(commands.find(c=>c.phase==="initialize-cluster")!));assert.ok(credentialPath);assert.ok(!existsSync(credentialPath));}
 for(const path of ["C:/ProbeInput","C:/ProbeOutput/child",TARGET.pgdata,"C:/Users/James.Massaro/Projects/fi-forgot/.orchestra/qualification/child"]){assert.throws(()=>assertPrivateCredentialBase(path),/host-mapped/);}assert.doesNotThrow(()=>assertPrivateCredentialBase("C:/Windows/Temp"));

 if(process.platform==="win32"){let aclDirectory="",initCalls=0;const deniedAcl=createSystemExecutionAdapter({credentialBase:realpathSync(tmpdir()),spawnSync:((program:string,args:string[])=>{if(program==="icacls"){aclDirectory=args[0];assert.ok(!existsSync(aclDirectory+"/password.txt"));assert.deepEqual(args.slice(1),["/inheritance:r","/grant:r","*S-1-5-18:(OI)(CI)F"]);return{status:1};}initCalls++;return{status:0};})as any});await assert.rejects(async()=>deniedAcl.run(commands.find(c=>c.phase==="initialize-cluster")!));assert.equal(initCalls,0);assert.ok(aclDirectory);assert.ok(!existsSync(aclDirectory));}
 let missingCalls=0;delete process.env.BRAIN_QUALIFICATION_ADMIN_PASSWORD;try{const missing=createSystemExecutionAdapter({credentialBase:realpathSync(tmpdir()),spawnSync:(()=>{missingCalls++;return{status:0};})as any});await assert.rejects(async()=>missing.run(commands.find(c=>c.phase==="initialize-cluster")!),/credential/);assert.equal(missingCalls,0);}finally{process.env.BRAIN_QUALIFICATION_ADMIN_PASSWORD=adminSecret;}
 assert.equal(maySkipPreInitializationRecovery([],false),true);assert.equal(maySkipPreInitializationRecovery([],true),false);assert.equal(maySkipPreInitializationRecovery(["initialize-cluster"],false),false);assert.equal(maySkipPreInitializationRecovery(["initialize-cluster"],true),false);
 const originalFailure=new Error("original initialization failed"),recoveryFailure=new Error("unowned partial target");await assert.rejects(executeFutureQualification(exact,{inspect:observed,run(){throw originalFailure;},recover(completed){assert.deepEqual(completed,[]);throw recoveryFailure;}}),(error:any)=>error instanceof AggregateError&&error.cause===originalFailure&&error.errors[0]===originalFailure&&error.errors[1]===recoveryFailure);
}finally{for(const[name,value]of Object.entries({BRAIN_QUALIFICATION_ADMIN_PASSWORD:previous.admin,BRAIN_QUALIFICATION_APP_PASSWORD:previous.app,PGPASSWORD:previous.pg,DATABASE_URL:previous.url,BRAIN_QUALIFICATION_ADMIN_DATABASE_URL:previous.adminUrl})){if(value===undefined)delete process.env[name];else process.env[name]=value;}}
console.log("phase-specific admin/app credential routing and bounded noninteractive role creation: PASS (fake subprocess adapter)");

assert.deepEqual(subprocessFailureMetadata({status:null,signal:'SIGTERM',error:Object.assign(new Error('secret'),{code:'ETIMEDOUT'})}),{status:null,signal:'SIGTERM',errorCode:'ETIMEDOUT'});assert.ok(!JSON.stringify(subprocessFailureMetadata({status:1,signal:'secret',error:{code:'secret'}})).includes('secret'));
const browserIndex=phases.indexOf('browser-workflow');assert.ok(browserIndex>0);assert.equal(phases[browserIndex-1],'record-postgres-restart-proof');assert.equal(phases[browserIndex+1],'stop-api-final');
for(const phase of ['browser-workflow','assert-after-restart'])assert.equal(buildPlan().find(command=>command.phase===phase)?.mutates,true,'GET-driven materialization must be declared');
