import assert from"node:assert/strict";
// @ts-ignore Node built-in type stripping requires runtime extensions.
import{assertOwnedCleanupEvidence,executeFutureQualification,type ExecutionAdapter}from"./execution.ts";
// @ts-ignore Node built-in type stripping requires runtime extensions.
import{EXACT_AUTHORIZATION,TARGET,type PlannedCommand}from"./plan.ts";
const exact={execute:true,syntheticRunDate:"2031-04-05",osBoundary:"reviewed-loopback-only",authorization:EXACT_AUTHORIZATION,host:TARGET.host,port:TARGET.port,database:TARGET.database,role:TARGET.role,pgdata:TARGET.pgdata,postgresMajor:16,disposable:true,catalogApproved:true,hashesApproved:true,credentialEnv:"PGPASSWORD"};
const observed=()=>({resolvedPgdata:TARGET.pgdata,targetExists:false,parentApproved:true,postgresMajor:16,sqlHashesVerified:true,baselineHashVerified:true,catalogState:"absent"as const});
const calls:PlannedCommand[]=[];let recovered:string[]|null=null;const fake:ExecutionAdapter={inspect:observed,run:c=>{calls.push(c);return c.phase==="identity"?`${TARGET.database}|${TARGET.role}|16`:"";},recover:x=>{recovered=[...x]}};
await executeFutureQualification(exact,fake);const phases=calls.map(x=>x.phase);for(const phase of["initialize-cluster","mark-owned-cluster","start-postgres","create-role","create-database","identity","fresh-baseline","fixtures","start-api","wait-api","assert","stop-api","restart-api","wait-api-after-restart","assert-after-restart","stop-api-final","stop-postgres"])assert.ok(phases.includes(phase),`missing ${phase}`);
for(const c of calls){assert.ok(c.program);assert.ok(Array.isArray(c.args));assert.ok(!c.args.some(x=>/<[^>]+>/.test(x)));}
let untouched=0;await executeFutureQualification({execute:false},{inspect(){untouched++;throw 0},run(){untouched++;return""}});assert.equal(untouched,0);
for(const denied of[{...exact,authorization:"wrong"},{...exact,hashesApproved:false},{...exact,catalogApproved:false},{...exact,disposable:false},{...exact,host:"localhost"}])await assert.rejects(()=>executeFutureQualification(denied,fake),/FAIL_CLOSED/);
for(const bad of[{...observed(),sqlHashesVerified:false},{...observed(),baselineHashVerified:false},{...observed(),targetExists:true},{...observed(),postgresMajor:15}])await assert.rejects(()=>executeFutureQualification(exact,{...fake,inspect:()=>bad}),/FAIL_CLOSED/);
const failing:ExecutionAdapter={inspect:observed,run:c=>{if(c.phase==="fixtures")throw new Error("fixture failure");return c.phase==="identity"?`${TARGET.database}|${TARGET.role}|16`:"";},recover:x=>{recovered=[...x]}};await assert.rejects(()=>executeFutureQualification(exact,failing),/fixture failure/);assert.ok(Array.isArray(recovered));const receipt=recovered as unknown as string[];assert.ok(receipt.includes("fresh-baseline"));assert.ok(!receipt.includes("fixtures"));
console.log("future typed execution admission/order/hash/identity/recovery tests: PASS (fake adapter only)");
assert.doesNotThrow(()=>assertOwnedCleanupEvidence({resolvedPgdata:TARGET.pgdata,marker:"fi-forgot-brain-qualification-owned-v1\n",postgresMajor:"16\n",postgresStopped:true,portReleased:true}));for(const bad of[{resolvedPgdata:"C:/wrong",marker:"fi-forgot-brain-qualification-owned-v1\n",postgresMajor:"16",postgresStopped:true,portReleased:true},{resolvedPgdata:TARGET.pgdata,marker:"wrong",postgresMajor:"16",postgresStopped:true,portReleased:true},{resolvedPgdata:TARGET.pgdata,marker:"fi-forgot-brain-qualification-owned-v1\n",postgresMajor:"16",postgresStopped:false,portReleased:true}])assert.throws(()=>assertOwnedCleanupEvidence(bad),/FAIL_CLOSED/);
