import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{resolve}from"node:path";
const root=resolve(import.meta.dirname,"../../.."),fixture=JSON.parse(readFileSync(resolve(root,"docs/brain-qualification-preparation/synthetic-fixtures.json"),"utf8"));
assert.equal(fixture.fixtureVersion,2);assert.equal(fixture.qualificationTiming.previewDays,14);assert.equal(fixture.qualificationTiming.runDateEnvironment,"BRAIN_QUALIFICATION_SYNTHETIC_RUN_DATE");assert.equal(fixture.qualificationTiming.sourceObservationTimesRemainNull,true);assert.ok(Object.keys(fixture.qualificationTiming.birthdayOffsetsDays).length>3);assert.equal(fixture.owners.length,2);assert.equal(fixture.recipients.length,7);assert.equal(new Set(fixture.recipients.map((x:{id:string})=>x.id)).size,7);
const ownerIds=new Set(fixture.owners.map((x:{id:string})=>x.id));for(const r of fixture.recipients)assert.ok(ownerIds.has(r.userId));
const recipientKeys=["id","userId","firstName","relationshipType","birthday","anniversary"],answerKeys=["id","userId","recipientId","eventType","eventYear","questionKey","questionText","answerText","wasSkipped","triggerType","importanceScore","archivedAt"];
for(const r of fixture.recipients)assert.deepEqual(Object.keys(r),recipientKeys);for(const a of fixture.questionAnswers)assert.deepEqual(Object.keys(a),answerKeys);
assert.ok(fixture.questionAnswers.some((x:{wasSkipped:boolean})=>x.wasSkipped));assert.ok(fixture.questionAnswers.some((x:{archivedAt:string|null})=>x.archivedAt));assert.ok(fixture.recipients.filter((x:{userId:string;birthday:string|null})=>x.userId==="brain-qual-owner-a"&&x.birthday).length>3);assert.ok(fixture.recipients.some((x:{id:string;birthday:null})=>x.id===fixture.expected.restrainedRecipientId&&x.birthday===null));
assert.equal(fixture.expected.standaloneOpportunityPersistenceClaimed,false);assert.equal(fixture.expected.authenticatedIsolationQualified,false);assert.equal(fixture.expected.maximumOriginalEligibleSlots,3);assert.equal(fixture.expected.backfill,false);
console.log("brain qualification fixture schema verification: PASS; eligibility remains production-derived");

assert.deepEqual(fixture.personalRecipientDefaults,{customDates:[],selectedEvents:[],favoriteMemories:'',insideJokes:''});
