// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/concept-action-first/Dashboard.tsx": () => import("../components/mockups/concept-action-first/Dashboard.tsx"),
  "./components/mockups/concept-action-first/Mobile.tsx": () => import("../components/mockups/concept-action-first/Mobile.tsx"),
  "./components/mockups/concept-action-first/Profile.tsx": () => import("../components/mockups/concept-action-first/Profile.tsx"),
  "./components/mockups/concept-memory-vault/Dashboard.tsx": () => import("../components/mockups/concept-memory-vault/Dashboard.tsx"),
  "./components/mockups/concept-memory-vault/Mobile.tsx": () => import("../components/mockups/concept-memory-vault/Mobile.tsx"),
  "./components/mockups/concept-memory-vault/Profile.tsx": () => import("../components/mockups/concept-memory-vault/Profile.tsx"),
  "./components/mockups/concept-upcoming-moments/Dashboard.tsx": () => import("../components/mockups/concept-upcoming-moments/Dashboard.tsx"),
  "./components/mockups/concept-upcoming-moments/Mobile.tsx": () => import("../components/mockups/concept-upcoming-moments/Mobile.tsx"),
  "./components/mockups/concept-upcoming-moments/Profile.tsx": () => import("../components/mockups/concept-upcoming-moments/Profile.tsx"),
  "./components/mockups/concept-your-people/Dashboard.tsx": () => import("../components/mockups/concept-your-people/Dashboard.tsx"),
  "./components/mockups/concept-your-people/Mobile.tsx": () => import("../components/mockups/concept-your-people/Mobile.tsx"),
  "./components/mockups/concept-your-people/Profile.tsx": () => import("../components/mockups/concept-your-people/Profile.tsx")
};
