import assert from 'node:assert/strict';import * as React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {normalizeTimelineItem} from '../app/timeline/timelineDomain';import {timelineService} from '../app/api/services/timelineService';import {changeHypothesisOperation} from '../app/timeline/understandingTimelineOperations';
(globalThis as typeof globalThis&{React:typeof React}).React=React;const {FiTimelineItem}=await import('../app/components/timeline/FiTimelineItem');
const date='2026-09-10T00:00:00.000Z';const item=normalizeTimelineItem({id:'h',type:'hypothesis',date,label:'Brain hypothesis: communication preference',summary:'Current evidence mentions phone.',source:'Server-owned Brain',sourceKind:'brain_hypothesis',semanticClassification:'uncertain_hypothesis',uncertain:true,lifecycleState:'active',revision:1,version:1,explanation:'One independent observation supports this possibility; not probability.',uncertainty:'May be contextual.',confidence:null,evidenceState:'support',support:[{observationVersionId:'v1'}],conflict:[],dependencyVersionIds:['v1'],history:[{id:'hv1',version:1,text:'phone',lifecycleState:'active',recordedAt:date}],actionHistory:[]})!;
const html=renderToStaticMarkup(React.createElement(FiTimelineItem,{item,onHypothesisAction:()=>{}}));for(const text of ['Brain hypothesis','not probability','Uncertainty','Confirm as helpful','Disagree','confidence unknown'])assert.ok(html.includes(text));assert.ok(!html.includes('User-authored interpretation'));assert.ok(!html.includes('Withdraw response'));
const responded=renderToStaticMarkup(React.createElement(FiTimelineItem,{item:{...item,responseState:'confirmed'},onHypothesisAction:()=>{}}));assert.ok(responded.includes('Withdraw response'));assert.ok(!responded.includes('Deliberately reverse'));assert.ok(!responded.includes('Confirm as helpful'));
const withdrawn=renderToStaticMarkup(React.createElement(FiTimelineItem,{item:{...item,responseState:'withdrawn'},onHypothesisAction:()=>{}}));assert.ok(withdrawn.includes('Deliberately reverse withdrawal'));assert.ok(!withdrawn.includes('Confirm as helpful'));
let body:any;const original=globalThis.fetch;globalThis.fetch=async(_url,options)=>{body=JSON.parse(String(options?.body));return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json'}})};try{await timelineService.changeHypothesis('r','h','disagree',1,'op');assert.deepEqual(body,{expectedRevision:1,operationId:'op'});}finally{globalThis.fetch=original;}
let writes=0;const service={...timelineService,async changeHypothesis(){writes++;throw Error('ambiguous');},async getTimeline(){return{items:[{...item,revision:2,actionHistory:[{operationId:'op',action:'disagree',actorUserId:'u',actedAt:date,expectedRevision:1,newRevision:2}]}]};}};const outcome=await changeHypothesisOperation('r',item,'disagree',service,'op');assert.equal(outcome.kind,'confirmed_after_ambiguous_write');assert.equal(writes,1,'ambiguous writes are never retried');
console.log('evolving understanding timeline transport passed');
