import {readFileSync} from "node:fs";
import {currentOpportunityFollowThrough} from "../app/concierge-brain/currentOpportunityFollowThrough.js";
import {mutateOpportunityFollowThrough} from "../app/concierge-brain/mutateOpportunityFollowThrough.js";
const event={id:"one",lineageId:"lineage",version:1,action:"set",active:true} as any;
if(currentOpportunityFollowThrough([event,{...event,id:"two",version:2,action:"withdraw",active:false}]).length)throw Error("withdrawn report remained current");
let request:any;globalThis.fetch=(async(path:any,init:any)=>{request={path:String(path),init};return new Response(JSON.stringify({followThrough:event}),{status:201,headers:{"Content-Type":"application/json"}})}) as typeof fetch;
await mutateOpportunityFollowThrough({recipientId:"recipient",opportunityId:"recipient:birthday",occurrenceCycleId:null,dimension:"action",value:"planned",expectedVersion:0,idempotencyKey:"stable-key"});
if(request.path!=="/api/v2/concierge/opportunity-follow-through"||request.init.method!=="POST")throw Error("production transport not invoked");
await mutateOpportunityFollowThrough({recipientId:"recipient",followThroughEventId:"one",dimension:"outcome",value:"appreciated",expectedVersion:0,idempotencyKey:"outcome-key"});
if(!String(request.init.body).includes('"followThroughEventId":"one"')||!String(request.init.body).includes('"dimension":"outcome"'))throw Error("retained historical outcome transport missing");
const panel=readFileSync(new URL("../app/components/ai-concierge/FiConciergeWorkspacePanel.tsx",import.meta.url),"utf8"),hook=readFileSync(new URL("../app/ai-concierge/hooks/useAiConciergeWorkspace.ts",import.meta.url),"utf8");
for(const label of ["Planned","I completed it","Not completed","Dismissed","No longer relevant","Went well","Went poorly","Appreciated","Unnecessary","Withdraw"])if(!panel.includes(label))throw Error(`missing accessible control ${label}`);
if(!panel.includes("Links and clicks do not verify")||!panel.includes("Retained Opportunity")||!hook.includes("followThroughRetryRef")||!readFileSync(new URL("../app/concierge-brain/followThroughMutation.ts",import.meta.url),"utf8").includes("Save status is uncertain"))throw Error("truthful retained/retry behavior missing");
const react=await import("react");Object.assign(globalThis,{React:react});const {renderToStaticMarkup}=await import("react-dom/server");const {FiConciergeWorkspacePanel}=await import("../app/components/ai-concierge/FiConciergeWorkspacePanel.js");
const retained={...event,recipientId:"recipient",opportunityId:"gone:birthday",occurrenceCycleId:"cycle",dimension:"action",value:"user_reported_completed",verification:"user_reported",sourceType:"brain_execution",sourceId:"birthday",family:"birthday"};
const workspace:any={opportunities:[],recommendations:[],insights:[],memories:[],suggestedConversations:[],defaults:{recommendationsTitle:"Suggestions",insightsTitle:"Insights",memoryTitle:"Memories"},aiDefaults:{emptyDescription:"Empty"},feedbackHistory:[],followThroughHistory:[retained],followThroughPending:null,followThroughStatus:"Report saved",submitFollowThrough:async()=>undefined};
const markup=renderToStaticMarkup(react.createElement(FiConciergeWorkspacePanel,{workspace,onPromptSelect:()=>undefined}));
for(const text of ["Retained Opportunity","Correct or add a report","Save correction","Save outcome","Report saved","reported by you"])if(!markup.includes(text))throw Error(`rendered retained workflow missing ${text}`);
const pending=renderToStaticMarkup(react.createElement(FiConciergeWorkspacePanel,{workspace:{...workspace,followThroughPending:"one",followThroughStatus:"Saving your report."},onPromptSelect:()=>undefined}));if(!pending.includes("Saving your report")||!pending.includes("disabled"))throw Error("rendered pending state missing");
console.log("opportunity follow-through controls passed");

const outcomeOnly=renderToStaticMarkup(react.createElement(FiConciergeWorkspacePanel,{workspace:{...workspace,followThroughHistory:[{...retained,dimension:'outcome',value:'appreciated'}]},onPromptSelect:()=>undefined}));
for(const text of ['Correct or add a report','Save correction','Save outcome','appreciated'])if(!outcomeOnly.includes(text))throw Error('Outcome-only retained report cannot be corrected: '+text);
const withdrawnOnly=renderToStaticMarkup(react.createElement(FiConciergeWorkspacePanel,{workspace:{...workspace,followThroughHistory:[retained,{...retained,id:'withdrawal',version:2,action:'withdraw',active:false}]},onPromptSelect:()=>undefined}));
if(withdrawnOnly.includes('Save correction'))throw Error('Superseded report presented as active');
console.log('Actual retained outcome-only correction and withdrawn current-state controls passed.');

const {reserveFollowThroughRequest,performFollowThroughMutation}=await import('../app/concierge-brain/followThroughMutation.js');
const retryCache=new Map();const statuses:string[]=[],pendingStates:Array<string|null>=[];let reloads=0,transportAttempts=0;const sentBodies:string[]=[];
const intent={recipientId:'recipient',followThroughEventId:'stored-action',dimension:'outcome' as const,value:'appreciated' as const,expectedVersion:0};
const reserved=reserveFollowThroughRequest(retryCache,intent,()=> 'stable-real-request');
globalThis.fetch=(async(_url:any,init:any)=>{sentBodies.push(init.body);transportAttempts++;if(transportAttempts===1)throw Error('lost response');return new Response(JSON.stringify({followThrough:retained}),{status:201,headers:{'Content-Type':'application/json'}});}) as typeof fetch;
const operation=(r:typeof reserved,reload=async()=>{reloads++})=>performFollowThroughMutation({...r,cache:retryCache,setPending:key=>pendingStates.push(key),setStatus:status=>statuses.push(status),reload});
await operation(reserved);if(!statuses.some(s=>s.includes('uncertain'))||retryCache.size!==1||reloads!==1||pendingStates.at(-1)!==null)throw Error('Uncertain operation did not retain retry and clear pending');
const retry=reserveFollowThroughRequest(retryCache,{...intent,expectedVersion:7},()=> 'must-not-be-used');await operation(retry);
if(sentBodies[0]!==sentBodies[1]||retryCache.size||!statuses.at(-1)?.includes('not external verification'))throw Error('Production retry changed original request after reload or failed to settle');
const occurrenceA=reserveFollowThroughRequest(retryCache,{recipientId:'recipient',opportunityId:'recipient:birthday',occurrenceCycleId:'2026',dimension:'action',value:'planned',expectedVersion:0},()=> 'occurrence-a');
const occurrenceB=reserveFollowThroughRequest(retryCache,{recipientId:'recipient',opportunityId:'recipient:birthday',occurrenceCycleId:'2027',dimension:'action',value:'planned',expectedVersion:0},()=> 'occurrence-b');
if(occurrenceA.reservation===occurrenceB.reservation)throw Error('New cycle reused an uncertain old-cycle request');
await operation(occurrenceB,async()=>{throw Error('reload unavailable')});if(statuses.at(-1)!=='Report saved, but refreshed history is unavailable.')throw Error('Known successful write was mislabeled uncertain after refresh failure');
const withdrawalIntent=reserveFollowThroughRequest(retryCache,{recipientId:'recipient',followThroughEventId:'stored-action',withdraw:true,expectedVersion:1},()=> 'withdraw-real-request');await operation(withdrawalIntent);if(!statuses.includes('Withdrawing report.')||statuses.at(-1)!=='Report withdrawn.')throw Error('Withdrawal operation status incorrect');
console.log('Actual hook operation: pending, uncertain response, stable replay across reload, new-cycle isolation, success, refresh failure, withdrawal passed.');
