/**
 * Color-system CSS custom property names.
 * Extends Phase 2 `--fi-color-*` primitives without replacing them.
 */
export const colorCssVar = {
  primary: "--fi-color-primary",
  primaryHover: "--fi-color-primary-hover",
  secondary: "--fi-color-secondary",
  accent: "--fi-color-accent",
  accentHover: "--fi-color-accent-hover",
  canvas: "--fi-color-canvas",
  surface: "--fi-color-surface",
  surfaceSecondary: "--fi-color-surface-secondary",
  surfaceTertiary: "--fi-color-surface-tertiary",
  surfaceElevated: "--fi-color-surface-elevated",
  textPrimary: "--fi-color-text-primary",
  textSecondary: "--fi-color-text-secondary",
  textMuted: "--fi-color-text-muted",
  textDisabled: "--fi-color-text-disabled",
  textInverse: "--fi-color-text-inverse",
  link: "--fi-color-link",
  divider: "--fi-color-divider",
  border: "--fi-color-border",
  borderHover: "--fi-color-border-hover",
  borderActive: "--fi-color-border-active",
  focus: "--fi-color-focus",
  hover: "--fi-color-hover",
  disabledBackground: "--fi-color-disabled-bg",
  disabledForeground: "--fi-color-disabled-fg",
  success: "--fi-color-success",
  successSubtle: "--fi-color-success-subtle",
  warning: "--fi-color-warning",
  warningSubtle: "--fi-color-warning-subtle",
  error: "--fi-color-danger",
  errorSubtle: "--fi-color-danger-subtle",
  info: "--fi-color-info",
  infoSubtle: "--fi-color-info-subtle",
  health: {
    excellent: "--fi-color-health-excellent",
    healthy: "--fi-color-health-healthy",
    needsAttention: "--fi-color-health-needs-attention",
    priority: "--fi-color-health-priority",
  },
  brownie: {
    gold: "--fi-color-brownie-gold",
    progress: "--fi-color-brownie-progress",
  },
  calendar: {
    upcoming: "--fi-color-calendar-upcoming",
    sent: "--fi-color-calendar-sent",
    draft: "--fi-color-calendar-draft",
    missed: "--fi-color-calendar-missed",
    autopilot: "--fi-color-calendar-autopilot",
  },
  notification: {
    info: "--fi-color-notification-info",
    success: "--fi-color-notification-success",
    warning: "--fi-color-notification-warning",
    danger: "--fi-color-notification-danger",
  },
  billing: {
    surface: "--fi-color-billing-surface",
    accent: "--fi-color-billing-accent",
    muted: "--fi-color-billing-muted",
  },
  admin: {
    surface: "--fi-color-admin-surface",
    text: "--fi-color-admin-text",
    accent: "--fi-color-admin-accent",
  },
} as const;
