export {
  adminPalette,
  billingPalette,
  brandPalette,
  browniePointsPalette,
  calendarPalette,
  darkPalette,
  feedbackPalette,
  neutralPalette,
  notificationPalette,
  relationshipHealthPalette,
} from "@/app/design/colors/palette";

export { colorCssVar } from "@/app/design/colors/cssVars";

export {
  colorAccessibility,
  getContrastRatio,
  meetsContrastRatio,
  verifiedContrastPairs,
  verifyPaletteContrast,
} from "@/app/design/colors/accessibility";

export {
  domainColorTokens,
  isSemanticColorRole,
  semanticColorMap,
  semanticColorRoles,
} from "@/app/design/colors/semantic";
export type { SemanticColorRole } from "@/app/design/colors/semantic";

export const colorUtilityClasses = {
  bgCanvas: "fi-bg-canvas",
  bgSurface: "fi-bg-surface",
  bgSurfaceSecondary: "fi-bg-surface-secondary",
  bgSurfaceTertiary: "fi-bg-surface-tertiary",
  bgSurfaceElevated: "fi-bg-surface-elevated",
  bgPrimary: "fi-bg-primary",
  bgPrimaryHover: "fi-bg-primary-hover",
  bgDisabled: "fi-bg-disabled",
  textPrimary: "fi-text-primary",
  textSecondary: "fi-text-secondary",
  textMuted: "fi-text-muted",
  textDisabled: "fi-text-disabled",
  textInverse: "fi-text-inverse",
  textLink: "fi-text-link",
  textSuccess: "fi-text-success",
  textWarning: "fi-text-warning",
  textError: "fi-text-error",
  textInfo: "fi-text-info",
  borderDefault: "fi-border-default",
  borderHover: "fi-border-hover",
  borderActive: "fi-border-active",
  borderFocus: "fi-border-focus",
  divider: "fi-divider",
  stateHover: "fi-state-hover",
  stateDisabled: "fi-state-disabled",
  bgSuccessSubtle: "fi-bg-success-subtle",
  bgWarningSubtle: "fi-bg-warning-subtle",
  bgErrorSubtle: "fi-bg-error-subtle",
  bgInfoSubtle: "fi-bg-info-subtle",
  healthExcellent: "fi-color-health-excellent",
  healthHealthy: "fi-color-health-healthy",
  healthNeedsAttention: "fi-color-health-needs-attention",
  healthPriority: "fi-color-health-priority",
  brownie: "fi-color-brownie",
  bgBrownieSubtle: "fi-bg-brownie-subtle",
  calendarUpcoming: "fi-color-calendar-upcoming",
  calendarSent: "fi-color-calendar-sent",
  calendarDraft: "fi-color-calendar-draft",
  calendarMissed: "fi-color-calendar-missed",
  calendarAutopilot: "fi-color-calendar-autopilot",
  notificationInfo: "fi-bg-notification-info",
  notificationSuccess: "fi-bg-notification-success",
  notificationWarning: "fi-bg-notification-warning",
  notificationDanger: "fi-bg-notification-danger",
  bgBilling: "fi-bg-billing",
  textBillingAccent: "fi-text-billing-accent",
  bgAdmin: "fi-bg-admin",
  textAdminAccent: "fi-text-admin-accent",
} as const;
